BR=["Equinox","In-N-Out","Trader Joe's","Lululemon","Lush","REI","Patagonia","IKEA","Supreme","SoulCycle","Aesop","Kith","Brandy Melville","Alo Yoga","Harley-Davidson","Costco","Sephora","Warby Parker","Chrome Hearts","Barry's","Chick-fil-A"]
_src=open('/tmp/gen/brands.py').read(); exec(_src[_src.index("S='fill"):_src.index('def card')])
def _tint(c):
    r,g,b=int(c[1:3],16),int(c[3:5],16),int(c[5:7],16); return f'rgb({round(r*0.12+224.4)}, {round(g*0.12+224.4)}, {round(b*0.12+224.4)})'
def brands(n=6):
    out=''.join(f'<a href="MExplore.dc.html" style="position: relative; overflow: hidden; display: flex; flex-direction: column; gap: 10px; padding: 18px 14px 12px; min-height: 138px; box-sizing: border-box; border-radius: 14px; background: #fff; border: 1px solid #e4ded2;"><span style="position: absolute; top: 0; left: 0; right: 0; height: 5px; background: {col};"></span><span style="width: 44px; height: 44px; border-radius: 12px; display: flex; align-items: center; justify-content: center; color: {col}; background: {_tint(col)};">{ico(k,24)}</span><span style="font-family: \'Cormorant Garamond\', Georgia, serif; font-size: {24 if len(nm)<12 else 20}px; line-height: 24px; margin-top: auto; white-space: nowrap;">{nm}</span><span class="xs" style="font-weight: 700; color: #237233;">✓ On the registry</span></a>' for slug,nm,cat,k,col in B[:n])
    out+='<a href="MExplore.dc.html" style="display: flex; flex-direction: column; justify-content: flex-end; gap: 4px; padding: 14px; min-height: 138px; box-sizing: border-box; border-radius: 14px; background: #13203a; color: #fff;"><span style="font-family: \'Cormorant Garamond\', Georgia, serif; font-size: 22px; line-height: 24px;">+ 12,400 more</span><span class="xs" style="color: #c9d0dc;">Find yours ⟶</span></a>'
    return '<div style="display: grid; grid-template-columns: 1fr 1fr; gap: 10px;">'+out+'</div>'
pubbar=f'<div class="ab">{LOGO}<span class="t" style="font-size: 16px;">Local AI Registry</span><a href="MExplore.dc.html" class="lk" style="font-size: 15px; text-decoration: none; padding: 0 6px;">Sign in</a><a class="bp sm" href="#" style="height: 40px; font-size: 14px; padding: 0 16px;">Join</a></div>'
exec(open('/tmp/gen/v4parts.py').read())
def _row(v,tt,biz,cat,when,who,how,ans,flag,n):
    bd={'owner':'<span class="pill g" style="height: 20px; font-size: 10px;">✓ Owner answered</span>','need':'<span class="pill r" style="height: 20px; font-size: 10px;">Needs an answer</span>'}.get(flag,'')
    an=f'<span class="sm" style="color: #3d4658; border-left: 3px solid #f5e3cc; padding-left: 8px;"><b>{who}</b> {ans}</span>' if ans else ''
    return f'<div class="post" style="padding: 11px 0;"><div class="vote">{ic(I["up"],16)}{v}</div><div class="g"><span class="meta"><b style="color: #13203a;">{biz}</b> · {when}</span><b>{tt}</b>{an}<span class="meta">{n} answers {bd}</span></div></div>'
exec(open('/tmp/gen/v8parts.py').read())
_BR=open('/tmp/gen/brands.py').read(); exec(_BR[_BR.index("S='fill"):_BR.index('def card')])
_BD={x[1]:x for x in B}
def _t(c,a=0.14):
    r,g,b=int(c[1:3],16),int(c[3:5],16),int(c[5:7],16); return f'rgb({round(r*a+255*(1-a))}, {round(g*a+255*(1-a))}, {round(b*a+255*(1-a))})'
def _fl(w,col,name,ml=0): return f'<span style="position: relative; display: inline-flex; margin-left: {ml}px;"><span style="position: absolute; left: 0; bottom: 12px; background: {col}; color: #fff; font-size: 9px; font-weight: 700; line-height: 14px; padding: 1px 5px; border-radius: 3px 3px 3px 0; white-space: nowrap;">{name}</span><span style="display: block; width: {w}px; height: 10px; background: {col}33; border-bottom: 2px solid {col};"></span></span>'
def _ln(w): return f'<span style="display: block; width: {w}px; height: 8px; border-radius: 4px; background: #e3e6ec;"></span>'
_SV='fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"'
_IC={'check':'<path d="M5 12l5 5 9-10"/>','chat':'<path d="M4 5h16v11H9l-5 4z"/>','cam':'<rect x="3" y="7" width="18" height="13" rx="3"/><circle cx="12" cy="13.5" r="3.5"/>','seal':'<path d="M6 3h9l4 4v14H6z"/><circle cx="12" cy="13" r="3"/>','tag':'<path d="M3 12V4h8l10 10-8 8z"/>','clock':'<circle cx="12" cy="12" r="8"/><path d="M12 8v4l3 2"/>','pin':'<path d="M12 21s7-6 7-12a7 7 0 0 0-14 0c0 6 7 12 7 12z"/>','phone':'<path d="M5 4h4l2 5-3 2a11 11 0 0 0 5 5l2-3 5 2v4a2 2 0 0 1-2 2A16 16 0 0 1 3 6a2 2 0 0 1 2-2z"/>','shield':'<path d="M12 3l8 3v6c0 5-4 8-8 9-4-1-8-4-8-9V6z"/>','star':'<path d="M12 3l2.7 5.6 6.1.9-4.4 4.3 1 6.1L12 17l-5.4 2.9 1-6.1-4.4-4.3 6.1-.9z" fill="currentColor"/>'}
def _i(k,s=12): return f'<svg width="{s}" height="{s}" viewBox="0 0 24 24" {_SV} aria-hidden="true">{_IC[k]}</svg>'
def _fr(icon,lw,vw,col=None,src=None):
    v=(f'<span style="position: relative; display: inline-flex;"><span style="position: absolute; left: -8px; top: -9px; width: 16px; height: 16px; border-radius: 50%; background: {col}; color: #fff; display: flex; align-items: center; justify-content: center; box-shadow: 0 0 0 2px #fff;">{_i(src,9)}</span><span style="display: block; width: {vw}px; height: 10px; background: {col}2e; border-bottom: 2px solid {col};"></span></span>' if col else _ln(vw))
    return f'<div style="display: flex; align-items: center; gap: 8px; height: 30px; border-bottom: 1px solid #f1f3f6;"><span style="color: #b4bac5; display: flex;">{_i(icon,12)}</span>{_ln(lw)}<span style="flex: 1;"></span>{v}</div>'
def _hl(w,col,src): return f'<span style="position: relative; display: inline-flex;"><span style="position: absolute; left: -8px; top: -10px; width: 16px; height: 16px; border-radius: 50%; background: {col}; color: #fff; display: flex; align-items: center; justify-content: center; box-shadow: 0 0 0 2px #fff;">{_i(src,9)}</span><span style="display: block; width: {w}px; height: 10px; background: {col}2e; border-bottom: 2px solid {col};"></span></span>'
def _line(*p): return '<div style="display: flex; align-items: center; gap: 6px; height: 10px;">'+''.join(p)+'</div>'
def _fl(col,x,y,icon='chat',img=False):
    left=(f'<span style="width: 20px; height: 20px; border-radius: 6px; background: #e6e9ee; flex-shrink: 0;"></span>' if img else f'<span style="width: 18px; height: 18px; border-radius: 50%; background: {col}; flex-shrink: 0;"></span>')
    return f'<div style="position: absolute; left: {x}px; top: {y}px; width: 120px; display: flex; align-items: center; gap: 6px; padding: 7px 8px; border-radius: 10px; background: #fff; border: 1px solid #e4ded2; {"border-left: 3px solid "+col+";" if not img else ""} box-shadow: 0 10px 24px rgba(19,32,58,0.16); z-index: 3;">{left}<span style="display: flex; flex-direction: column; gap: 4px; flex: 1;">{_ln(60)}{_ln(36)}</span><span style="color: {col}; display: flex;">{_i(icon,10)}</span></div>'
_card='<div style="position: absolute; left: 26px; top: 30px; width: 298px; border-radius: 14px; background: #fff; border: 1px solid #e4ded2; box-shadow: 0 16px 40px rgba(19,32,58,0.14); overflow: hidden;"><div style="display: grid; grid-template-columns: 2fr 1fr 1fr; grid-template-rows: 32px 32px; gap: 3px;"><span style="background: #e6e9ee; grid-row: span 2;"></span><span style="background: #e0f2f3; border: 2px solid #0e9aa7;"></span><span style="background: #e6e9ee;"></span><span style="background: #e6e9ee;"></span><span style="background: #e6e9ee;"></span></div><div style="padding: 10px 14px 14px; display: flex; flex-direction: column; gap: 9px;"><b style="font-family: Cormorant Garamond, Georgia, serif; font-size: 22px; font-weight: 500; line-height: 24px;">Main Street Med Spa</b><span style="display: flex; gap: 2px; color: #c9ced8;">'+_i('star',10)*5+'</span>'+_line(_ln(70),_hl(60,'#d6457a','chat'),_ln(50))+_line(_ln(190))+_line(_ln(40),_ln(70),_hl(54,'#7c4dff','seal'))+'<div style="display: flex; gap: 6px;"><span style="width: 52px; height: 18px; border-radius: 9px; background: #f1f3f6;"></span><span style="position: relative; width: 52px; height: 18px; border-radius: 9px; background: #1f9d551f; border: 2px solid #1f9d55; box-sizing: border-box;"></span><span style="width: 52px; height: 18px; border-radius: 9px; background: #f1f3f6;"></span></div>'+_line(_ln(40),_hl(64,'#e8740c','chat'))+'</div></div>'
_doc='<div style="position: relative; height: 330px; margin: 0 -8px;">'+_card+_fl('#0e9aa7',210,0,'cam',True)+_fl('#d6457a',0,150)+_fl('#e8740c',220,230)+_fl('#7c4dff',30,292,'seal',True)+_fl('#13203a',200,292,'check')+'</div>'
home1=pubbar+f'''<div class="bd" style="gap: 12px; padding-top: 6px;"><h1 class="T" style="font-size: 40px; line-height: 41px;">What locals know, <b style="color: #e5482d; font-weight: 700;">AI recommends</b>.</h1><span class="sm mu" style="margin-top: -4px;">Reviews can be bought. Your neighbors can&#39;t. Their tips become the public record AI reads, pointing people to the places that earn it.</span><div style="margin-bottom: 24px;">{_doc}</div><a class="srch" href="MExplore.dc.html">{ic(I["search"],20)}Search a place, or ask</a><a href="MPublic.dc.html" style="align-self: center; font-size: 13px; color: #3d4658;">Own a business? <b style="color: #13203a;">See if AI recommends you</b> ⟶</a></div>'''+tabbar('pub','Explore')
def _tc(n,q,u,v,a,w):
    slug,nm,cat,k,col=_BD[n]
    return f'<div style="display: grid; grid-template-columns: 1fr 1fr; width: {w}px; height: 136px; flex-shrink: 0; border-radius: 12px; overflow: hidden; background: #fff; border: 1px solid #e4ded2;"><span style="background: #fff; border-right: 1px solid #f0ebe1; display: flex; flex-direction: column;"><span style="flex: 1; display: flex; align-items: center; justify-content: center; text-align: center; padding: 6px;"><span style="font-family: Cormorant Garamond, Georgia, serif; font-size: 17px; line-height: 18px;">{nm}</span></span><span style="height: 30px; background: linear-gradient(135deg,#e9e4da,#dcd5c7);"></span><span style="font-size: 9px; line-height: 12px; padding: 4px 6px; color: #13203a; font-weight: 700; white-space: nowrap; overflow: hidden;"><span style="color: #e5482d;">●</span> Irvine Spectrum</span></span><span style="display: flex; gap: 8px; padding: 14px 12px;"><span style="display: flex; flex-direction: column; align-items: center; font-size: 9px; line-height: 11px; color: #b4bac5;"><span style="color: #e5482d;">▲</span><b style="font-size: 11px; color: #13203a;">{v}</b>▼</span><span style="display: flex; flex-direction: column; justify-content: space-between;"><b style="font-size: 11px; line-height: 14px;">"{q}"</b><span style="font-size: 9px; line-height: 11px; color: #8a93a3;">{u}</span></span></span></div>'
_EX=[("Costco","Which gas station has the shortest line?","costco_dad",36,13),("Chick-fil-A","Does the drive-thru move faster at lunch?","uci_junior",47,22),("REI","Worth joining the co-op for rentals?","hike_socal",31,10),("Warby Parker","Is the free eye exam worth booking?","four_eyes_oc",19,7)]
_ALL=TR+_EX
home2=pubbar+f'''<div class="bd" style="gap: 10px; padding-top: 18px;"><span style="font-size: 11px; font-weight: 700; letter-spacing: 0.14em; color: #e5482d;">● TRENDING RIGHT NOW</span><h2 class="T" style="font-size: 30px; line-height: 33px; margin-top: 2px;">Stars say it&#39;s good.<br>Locals say <b style="color: #e5482d; font-weight: 700;">what&#39;s good</b>.</h2><div style="margin: 14px -20px 0; overflow: hidden; display: flex; flex-direction: column; gap: 14px;"><div style="display: flex; gap: 12px; margin-left: -30px;">{"".join(_tc(*x,w) for x,w in zip(_ALL[0::3],[250,230,260,240]))}</div><div style="display: flex; gap: 12px; margin-left: -120px;">{"".join(_tc(*x,w) for x,w in zip(_ALL[1::3],[240,260,230,250]))}</div><div style="display: flex; gap: 12px; margin-left: -70px;">{"".join(_tc(*x,w) for x,w in zip(_ALL[2::3],[230,250,240,260]))}</div></div><span class="xs mu" style="text-align: center; margin-top: 4px;">Rows slide right to left</span></div>'''+tabbar('pub','Explore')
join=bk('Join Irvine')+f'''<div class="bd" style="gap: 14px;"><h1 class="T">Join <em>Irvine</em>.</h1><p class="mu" style="margin: 0;">Pick the one that is you. You can do both later.</p>
<a href="MLocals.dc.html" class="cd" style="gap: 8px; text-decoration: none;">{BUBBLE.replace('width="120" height="90"','width="84" height="63"')}<span class="ey">For locals</span><span class="T2">Share what you <em style="color: #e5482d;">know</em>.</span><span class="sm mu">Ask and answer. No account needed.</span><span class="bp sm" style="margin-top: 4px;">Post something</span></a>
<a href="MClaim.dc.html" class="cd pe" style="gap: 8px; text-decoration: none;">{STORE.replace('width="120" height="90"','width="84" height="63"')}<span class="ey">For owners</span><span class="T2">Claim your <em style="color: #e5482d;">record</em>.</span><span class="sm">Free. Fix what AI says about you.</span><span class="bp sm" style="margin-top: 4px;">Find my business</span></a></div>'''
biz1=pubbar+f'''<div class="bd" style="gap: 16px; padding-top: 16px;"><span class="ey">For business</span><h1 class="T" style="font-size: 44px; line-height: 44px;">Get AI to <em>recommend</em> you.</h1><p class="mu" style="margin: 0;">ChatGPT, Gemini and Claude already talk about your business. We make sure they get it right, then get you named first.</p>
<a class="bp r" href="MExplore.dc.html">See what AI says about you</a><span class="sm mu" style="text-align: center;">Free. Takes 30 seconds.</span>
<div class="cd" style="gap: 12px;"><span class="ey">What AI says today</span><div style="display: flex; align-items: center; gap: 14px;"><span class="big" style="color: #c13515;">38%</span><span class="sm">of AI answers about med spas in Irvine mention Lumen. Coastline gets 78%.</span></div></div></div>'''
def plan(n,p,d,hot=False): return f'<a href="MAccount.dc.html" class="cd" style="text-decoration: none; {"border: 2px solid #13203a; background: #fbf4ea;" if hot else ""} padding: 14px 16px; gap: 4px;"><span style="display: flex; justify-content: space-between; align-items: baseline;"><b style="font-size: 17px;">{n}{" <span class=\'pill n\' style=\'height: 20px; font-size: 10px; vertical-align: 2px;\'>Most picked</span>" if hot else ""}</b><span class="T2" style="font-size: 26px;">{p}<span class="xs mu" style="font-family: Figtree, sans-serif;">{"/mo" if p!="Free" else ""}</span></span></span><span class="sm mu">{d}</span></a>'
biz2=pubbar+f'''<div class="bd" style="gap: 10px; padding-top: 10px;"><h2 class="T" style="font-size: 32px; line-height: 34px;">Pick how fast.</h2><span class="sm mu" style="margin-top: -4px;">No contract. You approve every piece.</span>
{plan("Get listed","Free","Claim, fix your info, answer locals.")}{plan("Fix","$500","Your correct info on a new directory every day.")}{plan("Trust","$1,500","Plus review replies, press releases, Google posts.",True)}{plan("Authority","$3,000","Plus your website, articles and your story.")}</div>'''
signin=bk('')+f'''<div class="bd" style="gap: 18px;"><h1 class="T">Welcome <em>back</em>.</h1><span class="lb">Email or mobile</span><div class="inp f">priya@lumenirvine.com</div><span class="lb">Password</span><div class="inp">••••••••••</div><a class="lk" href="#" style="text-align: right;">Forgot it?</a><span style="flex: 1;"></span><div style="display: flex; align-items: center; gap: 10px;" class="sm mu"><span style="flex: 1; height: 1px; background: #dcd5c7;"></span>or<span style="flex: 1; height: 1px; background: #dcd5c7;"></span></div><a class="bp o" href="#">{ic(I["google"],20)}Continue with Google</a></div><div class="cta"><a class="bp" href="MOwner.dc.html">Sign in</a></div>'''
board('MPublic.dc.html','M1 · Mobile: homepage, join, for business','Mobile · Public','Bottom tab bar for locals (Explore, Search, Post, Alerts, Me). One idea per screen, 17px body, 44px+ tap targets, primary action within thumb reach.',
 [[scr('Homepage','Speaks to locals, and every owner reading it sees why they need to be here.',home1),scr('Homepage, scrolled','A sea of brands sliding by, each with its trending question.',home2),scr('Join your city','Two big cards. The illustration says which one is which before you read.',join),scr('For business','One promise, one button, one proof number.',biz1),scr('For business, plans','Four plans as stacked cards. Trust is pre-highlighted.',biz2),scr('Sign in','Password and Google. The button sits above the keyboard zone.',signin)]])
import sys as _s; _s.path.insert(0,'/tmp/gen'); from plates import plate as _pl
shiftm=pubbar+f'''<div class="bd" style="gap: 16px; padding-top: 12px;"><span class="ey">The shift</span><h2 class="T" style="font-size: 34px; line-height: 37px;">Somewhere nearby, a customer is asking <em>which business to trust</em>.</h2><span class="T2" style="font-size: 26px;">An assistant will name one. Right now, that one <em>is not you</em>.</span><div class="cd" style="align-items: center; background: #fbf6ec;">{_pl("coffee","ms",300,216)}</div><div style="display: flex; gap: 14px; overflow: hidden; margin: 0 -20px; padding: 0 20px;">{"".join(_pl(k,"mm"+k,120,86) for k in ["dental","salon","optometry"])}</div><span class="xs mu" style="text-align: center;">Plates scroll sideways on their own, like a ticker.</span></div>'''+tabbar('pub','Explore')
findm=pubbar+f'''<div class="bd np" style="background: #13203a; color: #fff; padding: 36px 24px; gap: 16px;"><span class="ey" style="color: #aeb6c6;">The findings</span><span style="font-family: 'Cormorant Garamond', Georgia, serif; font-size: 150px; line-height: 130px;">73<span style="color: #e5482d; font-size: 70px; vertical-align: top;">%</span></span><span style="font-family: 'Cormorant Garamond', Georgia, serif; font-size: 30px; line-height: 34px;">of local businesses are <em style="color: #e5482d;">never</em> recommended by AI.</span><div style="height: 8px; border-radius: 4px; background: rgba(255,255,255,0.15);"><div style="width: 73%; height: 100%; border-radius: 4px; background: #e5482d;"></div></div><span class="xs" style="color: #aeb6c6;">The number counts up from 0 as it scrolls into view.</span></div>'''+tabbar('pub','Explore')
indm=pubbar+f'''<div class="bd" style="gap: 12px; padding-top: 12px;"><span class="ey">The registry, by industry</span><h2 class="T" style="font-size: 34px;">The industries we <em>watch closest</em>.</h2><div class="chs"><span class="ch on">Plastic surgeons</span><span class="ch">Dispensaries</span><span class="ch">Eye doctors</span></div>{"".join(f'<div class="cd" style="flex-direction: row; gap: 12px; align-items: center; padding: 10px 12px;"><span style="font-family: Cormorant Garamond, Georgia, serif; font-size: 28px; width: 32px;">0{i+1}</span><span style="flex: 1; display: flex; flex-direction: column;"><b style="font-size: 15px; line-height: 19px;">{n}</b><span class="xs mu">{c} · AI Score {s}</span></span></div>' for i,(n,c,s) in enumerate([("Dr. Michael Jazayeri","Santa Ana",68),("Heavenly Plastic Surgery","Foothill Ranch",66),("Wave Plastic Surgery","Costa Mesa",55),("Renaissance Plastic Surgery","Newport Beach",47)]))}</div>'''+tabbar('pub','Explore')
stepm=pubbar+f'''<div class="bd" style="gap: 12px; padding-top: 12px;"><span class="ey">How it works</span><h2 class="T" style="font-size: 34px;">Three steps, and it is <em>free</em>.</h2><span style="font-family: 'Cormorant Garamond', Georgia, serif; font-size: 56px; line-height: 52px; color: #e5482d;">02</span><span class="T2">See what AI says.</span><span class="sm mu">Its AI Score, which assistants name it, and the verdict in plain English.</span><div class="cd" style="flex-direction: row; gap: 14px; align-items: center;"><span style="width: 84px; height: 84px; border-radius: 50%; border: 8px solid #237233; box-sizing: border-box; display: flex; align-items: center; justify-content: center; font-family: 'Cormorant Garamond', Georgia, serif; font-size: 40px;">93</span><span class="sm"><b>QUIKTOX Botox</b><br><span class="mu">Named by ChatGPT and Claude.</span></span></div><span class="xs mu">Each step card slides in as you reach it.</span></div>'''+tabbar('pub','Explore')
footm=f'''<div class="bd np" style="background: #0e1830; color: #d8dde8; padding: 28px 24px; gap: 18px;"><span style="display: flex; gap: 10px; align-items: center;">{LOGO}<b style="color: #fff;">Local AI Registry</b></span><span class="ey" style="color: #8a93a3;">Sign up for updates</span><div style="display: flex; gap: 8px;"><span style="flex: 1; height: 48px; border-radius: 24px; border: 1px solid #3a4763; display: flex; align-items: center; padding: 0 16px; color: #8a93a3; font-size: 15px;">you@business.com</span><span style="height: 48px; padding: 0 18px; border-radius: 24px; background: #fff; color: #13203a; display: flex; align-items: center; font-weight: 700; font-size: 14px;">Join</span></div>{"".join(f'<div style="display: flex; justify-content: space-between; padding: 14px 0; border-top: 1px solid #26324d; font-size: 16px; font-weight: 600; color: #fff;">{h}<span style="color: #8a93a3;">+</span></div>' for h in ["The registry","For owners","Company","Resources"])}<span style="font-family: 'Cormorant Garamond', Georgia, serif; font-size: 58px; line-height: 58px; color: #fff;">Local AI <em style="color: #e5482d;">Registry</em></span><span class="xs" style="color: #8a93a3;">© 2026 Local AI Registry · Privacy · Terms · Data policy · Opt out</span><div style="display: flex; gap: 8px;">{"".join(f"<span style='width: 38px; height: 38px; border-radius: 50%; border: 1px solid #3a4763; display: flex; align-items: center; justify-content: center; font-size: 11px; font-weight: 700;'>{a}</span>" for a in ["in","X","IG","f","TT","P"])}</div></div>'''
BOARDS.pop()
board('MPublic.dc.html','M1 · Mobile: homepage, join, for business','Mobile · Public','Bottom tab bar for locals (Explore, Search, Post, Alerts, Me). One idea per screen, 17px body, 44px+ tap targets, primary action within thumb reach. Row 2 marks where the live homepage sections and footer go.',
 [[scr('Homepage','Speaks to locals, and every owner reading it sees why they need to be here.',home1),scr('Homepage, scrolled','A sea of brands sliding by, each with its trending question.',home2),scr('Join your city','Two big cards. The illustration says which one is which before you read.',join),scr('For business','One promise, one button, one proof number.',biz1),scr('For business, plans','Four plans as stacked cards. Trust is pre-highlighted.',biz2),scr('Sign in','Password and Google. The button sits above the keyboard zone.',signin)],
  [scr('Home · Current sections','Placeholder: copy from the live homepage.',pubbar+'<div class="bd" style="justify-content: center;"><div style="border: 3px dashed #b9b0a0; border-radius: 14px; background: #ece6da; padding: 28px 22px; display: flex; flex-direction: column; gap: 10px;"><span class="ey">Placeholder</span><span class="T" style="font-size: 32px; line-height: 34px;">Insert current homepage sections here</span><span class="sm mu">Same sections, order and animations as the live mobile homepage.</span></div></div>'+tabbar('pub','Explore')),scr('Home · Current footer','Placeholder: copy from the live homepage.','<div class="bd" style="justify-content: center; background: #13203a;"><div style="border: 3px dashed #3a4763; border-radius: 14px; padding: 28px 22px; display: flex; flex-direction: column; gap: 10px; color: #fff;"><span class="ey" style="color: #aeb6c6;">Placeholder</span><span class="T" style="font-size: 32px; line-height: 34px; color: #fff;">Insert current footer here</span><span class="sm" style="color: #c9d0dc;">Same as the live mobile footer.</span></div></div>')]])
