MAP='''<svg viewBox="0 0 390 420" width="390" height="420" preserveAspectRatio="xMidYMid slice" aria-hidden="true" style="position: absolute; inset: 0;"><rect width="390" height="420" fill="#e8e2d4"/><g stroke="#f7f3ea" stroke-width="10" fill="none"><path d="M-10 120 L400 90"/><path d="M60 -10 L120 430"/><path d="M-10 300 L400 330"/><path d="M260 -10 L300 430"/></g><g stroke="#f7f3ea" stroke-width="4" fill="none"><path d="M-10 200 L400 210"/><path d="M180 -10 L200 430"/></g><path d="M300 200 q30 20 70 10 v60 q-40 10 -70 -10z" fill="#cfdcc5"/><path d="M20 340 q40 -20 90 0 v80 h-90z" fill="#cfdcc5"/></svg>'''
def pinx(x,y,t,on=False,c='#13203a'):
    return f'<span style="position: absolute; left: {x}px; top: {y}px; transform: translate(-50%,-100%); display: flex; flex-direction: column; align-items: center; z-index: 2;"><span style="padding: 5px 10px; border-radius: 14px; background: {"#13203a" if on else "#ffffff"}; color: {"#ffffff" if on else "#13203a"}; font-size: 13px; font-weight: 700; box-shadow: 0 2px 8px rgba(19,32,58,0.25); white-space: nowrap;">{t}</span><span style="width: 2px; height: 8px; background: {"#13203a" if on else "#ffffff"};"></span></span>'
top=f'<div style="position: absolute; top: 47px; left: 0; right: 0; padding: 8px 16px; display: flex; flex-direction: column; gap: 10px; z-index: 3;"><div class="srch">{ic(I["search"],20)}<span style="flex: 1;">Search Irvine</span>{ic(I["filter"],20)}</div><div class="chs"><span class="ch on">All</span><span class="ch">Beauty</span><span class="ch">Food</span><span class="ch">Health</span><span class="ch">Fitness</span></div></div>'
mapview=lambda pins: f'<div style="position: relative; height: 470px; flex-shrink: 0; overflow: hidden; margin-top: -47px;">{MAP}{pins}</div>'
PINS=pinx(110,300,'Lumen 58')+pinx(260,245,'Coastline 84')+pinx(300,350,'Derm + Co 79')+pinx(170,420,'Glow Bar 71')
def rrow(v,t,tag,who,n,need=False): return f'<div class="post"><div class="vote">{ic(I["up"],16)}{v}</div><div class="g"><b>{t}</b><span class="meta"><span class="pill l" style="height: 20px; font-size: 11px;">{tag}</span>{who}</span><span class="meta">{ic(I["chat"],14)} {n} answers{" · <span style=\'color: #b42318; font-weight: 700;\'>Needs an answer</span>" if need else ""}</span></div></div>'
FEED=rrow(41,'First time getting lip filler. Who will not overdo it?','Lumen','aisha_m · 2d',23)+rrow(18,'Parking at Spectrum on Saturday, which structure?','Irvine Spectrum','turtle_rock_ren · 5h',9)+rrow(7,'Does Dr. Nair do the lip filler herself or a nurse?','Lumen','irvine_regular_42 · 1h',0,True)
ex1=f'''<div class="bd np" style="position: relative;">{top}{mapview(PINS)}<div class="sh" style="position: absolute; top: 400px; bottom: 0; padding-bottom: 0; gap: 4px;"><span class="gr"></span><div style="display: flex; justify-content: space-between; align-items: center;"><b style="font-size: 17px;">Talked about in Irvine</b><span class="sm mu">Today</span></div>{FEED}</div></div>'''+tabbar('pub','Explore')
ex2=f'''<div class="ab" style="gap: 8px;"><div class="srch" style="flex: 1; height: 46px;">{ic(I["search"],18)}Search Irvine</div><a class="icb w" href="#">{ic(I["map"],20)}</a></div><div class="chs" style="padding: 0 16px;"><span class="ch on">All</span><span class="ch">Questions</span><span class="ch">Tips</span><span class="ch">Heads-up</span></div><div class="bd" style="gap: 0; padding-top: 6px;">{FEED}{rrow(12,'Best tacos open after 10 on a weeknight?','Food','night_owl_uci · 3h',14)}{rrow(5,'Is the Trader Joe\'s on Culver less busy on Sundays?','Trader Joe\'s','woodbridge_mom · 1d',6)}</div>'''+tabbar('pub','Explore')
SUG=[('store','Lumen Aesthetics','Med spa · Irvine Spectrum'),('store','Lumen Dental Studio','Dentist · Woodbridge'),('search','lumen lip filler','Search posts and places'),('chat','"Is Lumen worth it for Botox?"','Question · 12 answers')]
sg=''.join(f'<a href="{"MExplore.dc.html" if i<2 else "#"}" class="rw">{"<span class=\'av bl\' style=\'border-radius: 10px;\'>"+ic(I[k],20)+"</span>"}<span class="g"><b>{a}</b><span>{b}</span></span></a>' for i,(k,a,b) in enumerate(SUG))
srch=f'''<div class="ab" style="gap: 8px;"><div class="srch f" style="flex: 1; height: 46px;">{ic(I["search"],18)}<span style="color: #13203a;">lumen</span><span style="width: 2px; height: 20px; background: #2b59d9;"></span></div><span class="sm" style="font-weight: 600;">Cancel</span></div><div class="bd" style="gap: 0;">{sg}<a class="rw" href="MExplore.dc.html" style="justify-content: center;"><b style="font-size: 15px; color: #2b59d9;">See all results for "lumen"</b></a></div><div class="kb">{"".join("<div>"+"".join(f"<span>{k}</span>" for k in r)+"</div>" for r in ["qwertyuiop","asdfghjkl","zxcvbnm"])}<div><span style="flex: 2.4;">123</span><span style="flex: 6;">space</span><span style="flex: 2.4; background: #2b59d9; color: #fff;">search</span></div></div>'''
res=f'''<div class="ab" style="gap: 8px;"><a class="icb" href="#">{ic(I["back"])}</a><div class="srch" style="flex: 1; height: 46px; color: #13203a;">{ic(I["search"],18)}lumen</div></div><div class="bd" style="gap: 12px;"><span class="sm mu">2 places · 31 posts</span>
<a href="MProfile.dc.html" class="cd" style="flex-direction: row; gap: 12px; align-items: center;"><span class="av" style="width: 52px; height: 52px; border-radius: 12px;">LA</span><span style="flex: 1; display: flex; flex-direction: column;"><b>Lumen Aesthetics</b><span class="sm mu">Med spa · ★ 4.9 · 612 reviews</span><span class="xs mu">Irvine Spectrum · Open until 7</span></span><span class="pill r">58</span></a>
<a href="#" class="cd" style="flex-direction: row; gap: 12px; align-items: center;"><span class="av lt" style="width: 52px; height: 52px; border-radius: 12px;">LD</span><span style="flex: 1; display: flex; flex-direction: column;"><b>Lumen Dental Studio</b><span class="sm mu">Dentist · ★ 4.7 · 88 reviews</span><span class="xs mu">Woodbridge · Closed now</span></span><span class="pill o">64</span></a>
<span class="ey" style="margin-top: 6px;">Posts about Lumen</span>{rrow(41,'First time getting lip filler. Who will not overdo it?','Lumen','aisha_m · 2d',23)}</div>'''+tabbar('pub','Search')
sel=f'''<div class="bd np" style="position: relative;">{top}{mapview(pinx(110,300,'Lumen 58',True)+pinx(260,240,'Coastline 84')+pinx(300,345,'Derm + Co 79'))}<div class="sh" style="position: absolute; top: 380px; bottom: 0; padding-bottom: 0;"><span class="gr"></span><div style="display: flex; gap: 12px; align-items: flex-start;"><span class="av" style="width: 56px; height: 56px; border-radius: 12px;">LA</span><span style="flex: 1; display: flex; flex-direction: column;"><b style="font-size: 19px;">Lumen Aesthetics</b><span class="sm mu">Med spa · ★ 4.9 (612)</span><span class="sm mu">Open until 7 · 1.2 mi</span></span><a class="icb" href="#">{ic(I["x"],20)}</a></div>
<div style="display: grid; grid-template-columns: 1fr 1fr; gap: 10px;"><a class="bp" href="MProfile.dc.html">See the page</a><a class="bp o" href="MProfile.dc.html">Book</a></div><div class="cd" style="padding: 12px 14px; gap: 4px;"><span class="meta">{ic(I["chat"],14)} 23 answers · 2 days ago</span><b style="font-size: 15px;">First time getting lip filler. Who will not overdo it?</b></div></div></div>'''+tabbar('pub','Explore')
types=bk('Everything in Irvine')+f'''<div class="bd" style="gap: 0;">'''+''.join(f'<a class="rw" href="#"><span class="av bl" style="border-radius: 10px;">{ic(I[k],20)}</span><span class="g"><b>{a}</b><span>{b}</span></span>{ic(I["chev"],18)}</a>' for k,a,b in [('star','Beauty','Med spas, salons, lashes · 212'),('store','Food','Restaurants, cafes, bakeries · 640'),('help','Health','Dentists, doctors, eye care · 318'),('user','Fitness','Gyms, studios, yoga · 144'),('pin','Shopping','Spectrum, Woodbridge, Tustin · 520'),('home','Home','Plumbers, cleaners, movers · 276'),('card','Money','Banks, tax, insurance · 98'),('team','Kids','Schools, tutors, camps · 131')])+'</div>'+tabbar('pub','Search')
def best(r,n,s,sc,c,why): return f'<a href="MProfile.dc.html" class="cd" style="gap: 6px; padding: 14px;"><span style="display: flex; align-items: center; gap: 10px;"><span class="T2" style="width: 26px;">{r}</span><b style="flex: 1; font-size: 17px;">{n}</b><span class="pill {c}">{sc}</span></span><span class="sm mu" style="padding-left: 36px;">{s}</span><span class="sm" style="padding-left: 36px;">{why}</span></a>'
bestof=bk('')+f'''<div class="bd" style="gap: 10px;"><h1 class="T" style="font-size: 34px; line-height: 36px;">Best med spas in <em>Irvine</em>.</h1><span class="sm mu" style="margin-top: -4px;">Ranked by what locals say and what is confirmed. Updated Oct 1.</span>{best(1,'Coastline MedSpa','★ 4.8 · 1,102 reviews · Newport Beach','84','g','Locals say: "Never rushed, answers every question."')}{best(2,'Derm + Co','★ 4.9 · 640 reviews · Tustin','79','g','Locals say: "Board-certified doctor does every injection."')}{best(3,'Lumen Aesthetics','★ 4.9 · 612 reviews · Irvine Spectrum','58','r','Locals say: "Talked me down to half a syringe."')}</div>'''+tabbar('pub','Search')
board('MExplore.dc.html','M2 · Mobile: explore and search','Mobile · Explore and search','Map first with a draggable sheet. The sheet has three heights: peek, half, full. Search suggests places and questions as you type. Tapping a pin opens the place in the sheet, not a new page.',
 [[scr('Explore, map','Map on top, the sheet peeks with what people are talking about.',ex1),scr('Explore, list','Tap the map icon to go back. Filter chips stay on top.',ex2),scr('Typing a search','Places first, then posts. Big rows, easy to hit.',srch),scr('Search results: "lumen"','Places with AI Score, then posts that mention them.',res),scr('Lumen selected','Tapping a place opens it in the sheet. Two big buttons.',sel),scr('Everything in Irvine','Categories as a plain list with counts.',types),scr('Best med spas','Ranked cards with one line from locals each.',bestof)]])
