def gal(): return '<div style="display: grid; grid-template-columns: 2fr 1fr; grid-template-rows: 1fr 1fr; gap: 3px; height: 230px; flex-shrink: 0;"><span class="ph-img" style="grid-row: span 2; background: #f0dcc4; border-radius: 0;">Treatment room</span><span class="ph-img" style="background: #e3e6dc; border-radius: 0;">Dr. Nair</span><span class="ph-img" style="background: #dfe3ea; border-radius: 0; position: relative;">Results wall<span style="position: absolute; right: 8px; bottom: 8px; background: rgba(19,32,58,0.8); color: #fff; padding: 3px 8px; border-radius: 10px;">+48</span></span></div>'
pbar=f'<div class="ab" style="position: absolute; top: 47px; left: 0; right: 0; z-index: 3;"><a class="icb w" href="MExplore.dc.html">{ic(I["back"])}</a><span class="t"></span><a class="icb w" href="#">{ic(I["share"],20)}</a></div>'
def ptabs(on): return '<div class="tabs">'+''.join(f'<span class="{"on" if t==on else ""}">{t}</span>' for t in ['Locals','Services','Team','Visit','Reputation','Updates'])+'</div>'
stick=lambda on: f'<div class="ab" style="gap: 8px;"><a class="icb" href="#">{ic(I["back"])}</a><span class="t">Lumen Aesthetics</span><a class="icb" href="#">{ic(I["share"],20)}</a></div>'+ptabs(on)
bookbar='<div class="cta" style="flex-direction: row; align-items: center; gap: 12px; padding-top: 10px;"><span style="flex: 1; display: flex; flex-direction: column;"><b style="font-size: 15px;">Consult $75</b><span class="xs mu">Credited if you book</span></span><a class="bp" href="#" style="padding: 0 28px;">Request a visit</a></div>'
p1=f'''<div class="bd np" style="position: relative; margin-top: -47px;">{pbar}<div style="height: 47px; flex-shrink: 0;"></div>{gal()}<div style="padding: 16px 20px 0; display: flex; flex-direction: column; gap: 8px;"><span style="display: flex; gap: 8px; align-items: center;"><span class="pill l">Not claimed yet</span><span class="xs mu">Med spa · Irvine Spectrum</span></span><h1 class="T" style="font-size: 36px;">Lumen Aesthetics</h1><span class="sm">★ 4.9 · 612 reviews · <span style="color: #237233; font-weight: 700;">Open</span> until 7</span>
<div class="cd" style="flex-direction: row; align-items: center; gap: 12px; padding: 12px 14px;"><span class="pill r" style="height: 44px; min-width: 44px; justify-content: center; font-size: 17px; border-radius: 22px;">58</span><span style="flex: 1;" class="sm"><b>AI Score</b><br><span class="mu">AI names Lumen in 38% of answers</span></span>{ic(I["chev"],18)}</div>
<div style="display: flex; gap: 14px;" class="xs mu"><span><span class="mk c"></span> Confirmed</span><span><span class="mk v"></span> Visitor</span><span><span class="mk a"></span> AI guess</span></div></div></div>'''+bookbar
def rrow2(v,t,who,n,need=False): return f'<div class="post"><div class="vote">{ic(I["up"],16)}{v}</div><div class="g"><b>{t}</b><span class="meta">{who}</span><span class="meta">{ic(I["chat"],14)} {n} answers{" · <span style=\'color: #b42318; font-weight: 700;\'>Needs an answer</span>" if need else ""} · {ic(I["share"],13)}</span></div></div>'
p2=stick('Locals')+f'''<div class="bd" style="gap: 0; padding-top: 10px;"><a href="MLocals.dc.html" class="srch" style="height: 48px; margin-bottom: 6px; box-shadow: none; border: 1px solid #dcd5c7;">{ic(I["plus"],18)}Ask locals about Lumen</a>{rrow2(41,'First time getting lip filler. Who will not overdo it?','Question · aisha_m · 2d · went',23)}{rrow2(7,'Does Dr. Nair do the lip filler herself or a nurse?','Question · irvine_regular_42 · 1h',0,True)}{rrow2(19,'Heads-up: Saturday waits run about 25 minutes','Heads-up · turtle_rock_ren · 4d · went',6)}{rrow2(11,'Free parking in Structure B, level 3','Tip · spectrum_regular · 1w',2)}</div>'''+bookbar
def svc(n,cat,p,m='c'): return f'<div class="fr" style="align-items: center;"><span style="display: flex; flex-direction: column;"><b style="font-size: 16px;">{n}<span class="mk {m}"></span></b><span class="xs mu">{cat}</span></span><span class="v">{p}</span></div>'
p3=stick('Services')+f'''<div class="bd" style="gap: 8px; padding-top: 12px;"><div class="chs"><span class="ch on">All 10</span><span class="ch">Injectables</span><span class="ch">Skin</span><span class="ch">Laser</span></div><div class="cd" style="gap: 0; padding: 4px 16px;">{svc('Lip filler','Injectables · half or full syringe','from $450')}{svc('Botox','Injectables · per unit','$14')}{svc('Dermal filler, cheeks and jaw','Injectables','from $700')}{svc('Morpheus8, face','Skin · 3 sessions advised','$1,200','v')}{svc('Laser hair removal','Laser','Ask','a')}</div><span class="lk" style="font-size: 14px;">See all 10 services</span></div>'''+bookbar
p4=stick('Visit')+f'''<div class="bd" style="gap: 12px; padding-top: 12px;"><div class="cd" style="gap: 0; padding: 4px 16px;"><div class="fr"><span class="k">Today</span><span class="v">9 AM to 7 PM<span class="mk c"></span></span></div><div class="fr"><span class="k">Mondays</span><span class="v">Closed<span class="mk v"></span></span></div><div class="fr"><span class="k">Parking</span><span class="v">Free, Structure B, level 3<span class="mk c"></span></span></div><div class="fr"><span class="k">Phone</span><span class="v" style="color: #2b59d9;">(949) 555-0148</span></div></div>
<span class="T2" style="font-size: 24px;">Busy times</span><div style="display: flex; align-items: flex-end; gap: 6px; height: 90px;">{"".join(f'<span style="flex: 1; height: {h}%; border-radius: 4px 4px 0 0; background: {"#13203a" if h>70 else "#c9c3b6"};"></span>' for h in [20,35,60,85,95,70,45,30,25])}</div><div class="xs mu" style="display: flex; justify-content: space-between;"><span>9a</span><span>12p</span><span>3p</span><span>6p</span></div><span class="sm mu">Usually quiet now. Busiest Wed and Thu, noon to 2.<span class="mk a"></span></span></div>'''+bookbar
p5=stick('Updates')+f'''<div class="bd" style="gap: 0; padding-top: 12px;"><div class="chs" style="margin-bottom: 8px;"><span class="ch on">All 9</span><span class="ch">Instagram 3</span><span class="ch">Google 2</span><span class="ch">Press 1</span><span class="ch">Website 2</span></div>'''+''.join(f'<div class="post" style="gap: 12px;"><span class="ph-img" style="width: 76px; height: 76px; flex-shrink: 0; background: {c};"></span><div class="g"><span class="meta"><b style="font-size: 12px; color: #13203a;">{src}</b> · {d}</span><b style="font-size: 15px; line-height: 20px;">{t}</b><span class="meta">▲ {v} · {n} comments</span></div></div>' for src,d,t,c,v,n in [('Instagram','Sep 18','Before and after: half a syringe of lip filler. Subtle is the point.','#f0dcc4',311,14),('Press','Sep 14','Irvine Weekly: Pink ribbon walk raises $12,000','#e9e3d6',48,3),('Google post','Sep 5','Free validated parking in Structure B, level 3.','#e3e6dc',9,1),('Website','Sep 10','What filler cannot do, and when to say no.','#dfe3ea',12,0)])+'</div>'+bookbar
photos=bk('51 photos')+'<div class="chs" style="padding: 0 16px;"><span class="ch on">All</span><span class="ch">Results</span><span class="ch">Space</span><span class="ch">Team</span></div><div class="bd" style="padding: 12px 3px 0;"><div style="display: grid; grid-template-columns: repeat(3,1fr); gap: 3px;">'+''.join(f'<span class="ph-img" style="height: 128px; border-radius: 0; background: {c};"></span>' for c in ['#f0dcc4','#e3e6dc','#dfe3ea','#ece2d2','#e9e3d6','#f3e1cf']*3)+'</div></div>'
edit=f'''<div class="bd np" style="position: relative;"><div style="opacity: 0.6;">{p4.split('<div class="cta"')[0]}</div><div class="scrim"></div><div class="sh"><span class="gr"></span><b style="font-size: 20px;">Suggest an edit</b><span class="sm mu" style="margin-top: -8px;">Mondays · now says Closed</span><span class="lb">What is right?</span><div class="inp f">Open 10 AM to 4 PM</div><span class="lb">How do you know?</span><div class="chs" style="flex-wrap: wrap;"><span class="ch on">I went</span><span class="ch">I called</span><span class="ch">I work there</span></div><span class="xs mu">Lumen is told. If they accept it, you get credit.</span><a class="bp" href="#">Send suggestion</a></div></div>'''
book=f'''<div class="bd np" style="position: relative;"><div style="opacity: 0.6;">{p1.split('<div class="cta"')[0]}</div><div class="scrim"></div><div class="sh"><span class="gr"></span><b style="font-size: 20px;">Request a visit</b><span class="lb">Day</span><div class="chs"><span class="ch">Sat 26</span><span class="ch on">Tue 29</span><span class="ch">Wed 30</span><span class="ch">Thu 1</span></div><span class="lb">Time</span><div class="chs"><span class="ch on">Morning</span><span class="ch">Afternoon</span><span class="ch">Evening</span></div><span class="lb">For</span><div class="inp" style="justify-content: space-between;">Consultation <span class="mu">▾</span></div><a class="bp" href="#">Request a booking</a><span class="xs mu" style="text-align: center;">Takes 30 seconds. You will not be charged.</span></div></div>'''
hist=bk('Change history')+'<div class="bd" style="gap: 0;">'+''.join(f'<div class="rw" style="align-items: flex-start; padding: 12px 0;"><span class="g"><b>{f}</b><span><s>{o}</s> → {n}</span><span class="xs mu">{w}</span></span><span class="pill {c}">{s}</span></div>' for f,o,n,w,s,c in [('Mondays','Open 9 to 6','Closed','Suggested by turtle_rock_ren · Sep 22','Accepted','g'),('Consult price','Free','$75, credited','Owner · Sep 20','Confirmed','g'),('Who injects','Aestheticians','Dr. Nair or a nurse','irvine_regular_42 · Sep 19','Pending','o'),('Phone','(949) 555-0100','(949) 555-0148','Google profile · Sep 2','Confirmed','g'),('Parking','Street only','Structure B, level 3','spectrum_regular · Aug 30','Accepted','g')])+'</div>'
board('MProfile.dc.html','M3 · Mobile: business profile','Mobile · Business profile','Photos and AI Score up top. Once you scroll, the name and tabs stick to the top and the booking bar sticks to the bottom. Editing and booking open as sheets so you never lose your place.',
 [[scr('Profile, top','Gallery, name, rating, AI Score and the marks legend. Booking is always one tap away.',p1),scr('Locals tab','Tabs stick after scrolling. Asking is the first row.',p2),scr('Services tab','Filter chips by type. Prices right-aligned, marks after each name.',p3),scr('Visit tab','Hours, parking, phone, then busy times as a simple bar chart.',p4),scr('Updates tab','Source filters with counts. Every post says where it came from.',p5)],
  [scr('All photos','Three across, filters on top.',photos),scr('Suggest an edit','A sheet over the page. Answer, source, send.',edit),scr('Request a visit','Day and time as chips, not a date picker.',book),scr('Change history','Old crossed out, new, who, and status.',hist)]])
