def cflow(step,n=4): return f'<div class="stp" style="padding: 0 20px 6px;">{"".join(f"<i class=\'{"on" if i<=step else ""}\'></i>" for i in range(n))}</div>'
kody_mini=f'<div class="kbar" style="margin: 0; background: transparent; border: none; padding: 0; justify-content: center;"><span class="sm mu">Stuck? <a class="lk" href="#" style="font-size: 14px;">Book with Kody</a> or <a class="lk" href="#" style="font-size: 14px;">email support</a></span></div>'
def cscr(title,step,body,btn,stepl):
    return appbar(f'<a class="icb" href="#">{ic(I["back"])}</a>',f'<span class="sm mu" style="font-weight: 600;">{stepl}</span>','<span class="sm" style="font-weight: 600; padding-right: 6px;">Save and exit</span>',True)+cflow(step)+f'<div class="bd" style="gap: 14px; padding-top: 14px;">{body}</div><div class="cta"><a class="bp" href="#">{btn} <span>⟶</span></a>{kody_mini}</div>'
claim=cscr('',0,f'''{STORE.replace('width="120" height="90"','width="96" height="72"')}<h1 class="T">Claim <em>Lumen</em>. It is free.</h1><div class="cd" style="flex-direction: row; align-items: center; gap: 12px;"><span class="av" style="width: 48px; height: 48px; border-radius: 10px;">LA</span><span style="display: flex; flex-direction: column;"><b>Lumen Aesthetics</b><span class="sm mu">9891 Irvine Center Dr, Suite 210</span></span></div><span class="lb">Your mobile number</span><div class="inp f"><b style="margin-right: 10px;">+1 ▾</b>(949) 555-0<span style="width: 2px; height: 22px; background: #2b59d9;"></span></div><span class="xs mu">We text you a code. No password to remember.</span>''','Text me a code','Step 1 of 4 · Claim')
otp=cscr('',1,'''<h1 class="T">Type the code we <em>texted</em> you.</h1><span class="sm mu">Sent to (949) 555-0148. <a class="lk" href="#" style="font-size: 14px;">Change</a></span><div class="otp"><span>4</span><span>8</span><span>1</span><span class="f"></span><span></span><span></span></div><span class="sm mu">Did not get it? <b style="color: #13203a;">Resend in 0:24</b></span>''','Confirm code','Step 2 of 4 · Text code')
otp=otp.replace('<div class="cta">','<div class="cta" style="padding-bottom: 12px;">').replace(kody_mini,'')+''
otp=otp.replace('</div><div class="cta"','</div><div class="key" style="padding-bottom: 30px;">'+''.join(f'<span>{k}</span>' for k in '123456789 0⌫')+'</div><div class="cta"') if False else otp
def frow(k,v,m,fix=False):
    base=f'<div style="display: flex; flex-direction: column; gap: 8px; padding: 12px 0; border-bottom: 1px solid #ece6da;"><span class="ey">{k}</span><span style="font-size: 17px;">{v}<span class="mk {m}"></span></span>'
    if fix: return base+'<div class="inp f" style="height: 50px;">Tue to Sat, 9 to 6 · Thu until 8</div><div style="display: grid; grid-template-columns: 1fr 1fr; gap: 8px;"><span class="bp sm">Save</span><span class="bp sm o">Cancel</span></div></div>'
    return base+'<div style="display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 8px;"><span class="bp sm o" style="height: 40px; font-size: 14px;">Confirm</span><span class="bp sm o" style="height: 40px; font-size: 14px;">Fix</span><span class="bp sm o" style="height: 40px; font-size: 14px;">Not us</span></div></div>'
basics=cscr('',2,'<span class="ey" style="color: #13203a;">Confirm info · 1 of 5</span><h1 class="T" style="font-size: 34px; margin-top: -8px;">Is this <em>right</em>?</h1><div style="margin-top: -8px;">'+frow('Business name','Lumen Aesthetics','a')+frow('Address','9891 Irvine Center Dr, Suite 210','c')+frow('Phone','(949) 555-0148','c')+'</div><span class="xs mu" style="text-align: center;">Next: hours and Mondays</span>','Confirm and continue','Step 3 of 4 · Confirm info')
fix=cscr('',2,'<span class="ey" style="color: #13203a;">Confirm info · 1 of 5</span><h1 class="T" style="font-size: 34px; margin-top: -8px;">Is this <em>right</em>?</h1><div style="margin-top: -8px;">'+frow('Hours','Tue to Sat, 9 AM to 6 PM','a',True)+frow('Mondays','Closed','v')+'</div>','Confirm and continue','Step 3 of 4 · Confirm info')
SV=['Botox','Lip filler','Dermal filler','Filler dissolving','Morpheus8, face','Morpheus8 Body','Microneedling','Sculptra','Laser hair removal','Skin checks']
svcs=cscr('',2,'<span class="ey" style="color: #13203a;">Confirm info · 2 of 5</span><h1 class="T" style="font-size: 34px; margin-top: -8px;">What do you <em>offer</em>?</h1><span class="sm mu" style="margin-top: -6px;">Tap anything you do not offer.</span><div style="display: flex; flex-wrap: wrap; gap: 8px;">'+''.join(f'<span class="ch" style="height: 46px; {"text-decoration: line-through; color: #a0a0a0; background: #efeae0;" if s=="Skin checks" else "border-color: #13203a;"}">{s}</span>' for s in SV)+'<span class="ch" style="height: 46px; border-style: dashed;">+ Add</span></div>','Confirm and continue','Step 3 of 4 · Confirm info')
known=cscr('',2,'<span class="ey" style="color: #13203a;">Confirm info · 3 of 5</span><h1 class="T" style="font-size: 34px; margin-top: -8px;">Pick 3 to be <em>known for</em>.</h1><span class="sm mu" style="margin-top: -6px;">AI will say you are known for these first.</span><b class="sm">2 of 3 picked</b><div style="display: flex; flex-direction: column; gap: 8px;">'+''.join(f'<span class="ch" style="height: 50px; justify-content: flex-start; {"background: #fbf4ea; border: 2px solid #13203a;" if n else ""}">{"<span class=\'pill n\' style=\'width: 24px; height: 24px; padding: 0; justify-content: center; border-radius: 12px;\'>"+n+"</span>" if n else ""}{s}</span>' for s,n in [('Lip filler','1'),('Morpheus8, face','2'),('Botox',''),('Dermal filler',''),('Sculptra','')])+'</div>','Confirm and continue','Step 3 of 4 · Confirm info')
team=cscr('',2,'<span class="ey" style="color: #13203a;">Confirm info · 4 of 5</span><h1 class="T" style="font-size: 34px; margin-top: -8px;">Who <em>works</em> here?</h1><div style="display: flex; flex-direction: column;">'+''.join(f'<div class="rw"><span class="av lt">{a}</span><span class="g"><b>{n}</b><span>{r}</span></span><span class="lk" style="font-size: 14px;">{x}</span></div>' for a,n,r,x in [('PN','Dr. Priya Nair, MD','Owner · priya@lumenirvine.com','Edit'),('NR','Nadia Rahimi, RN','Nurse injector','Add email'),('JL','Jordan Lee, NP','Nurse injector','Add email'),('MO','Maya Ortiz','Front desk · maya@lumenirvine.com','Edit')])+'</div><span class="bp o sm">+ Add a person</span>','Confirm and continue','Step 3 of 4 · Confirm info')
links=cscr('',2,'<span class="ey" style="color: #13203a;">Confirm info · 5 of 5</span><h1 class="T" style="font-size: 34px; margin-top: -8px;">Where else are you <em>online</em>?</h1><div>'+''.join(f'<div class="fr"><span class="k">{k}</span><span class="v" style="font-weight: 500;">{v}<span class="mk {m}"></span></span></div>' for k,v,m in [('Website','lumenirvine.com','c'),('Booking','lumenirvine.com/book','a'),('Instagram','@lumenaesthetics','a'),('TikTok','@lumenaesthetics','a'),('Yelp','lumen-aesthetics-irvine','c')])+'</div>','Finish','Step 3 of 4 · Confirm info')
verify=cscr('',3,f'''{STORE_OK.replace('width="140" height="110"','width="110" height="86"')}<h1 class="T">Prove it is <em>yours</em>.</h1><p class="mu" style="margin: 0;">The fastest way: connect the Google Business Profile you already have.</p><div class="cd" style="gap: 8px;"><span class="sm">✓ We only read it. We never post or change anything.</span><span class="sm">✓ Takes about 20 seconds.</span><span class="sm">✓ Disconnect any time.</span></div><a class="lk" href="#">Other ways to verify</a>''','Connect Google','Step 4 of 4 · Verify')
board('MClaim.dc.html','M5 · Mobile: claim and set up','Mobile · Claim and set up','One question per screen. Progress bar on top, the next button always in the same spot at the bottom, and Kody or support one tap away on every step. No step needs scrolling.',
 [[scr('Claim','Your business, your mobile, one button.',claim),scr('Text code','Big boxes, auto-advance, resend timer.',otp),scr('Confirm basics','Three facts per screen, three big buttons each.',basics),scr('Tapped Fix','The row opens in place with the right answer typed in.',fix),scr('Services','Chips. Tap what you do not offer.',svcs)],
  [scr('Known for','Pick up to 3. Numbers show the order.',known),scr('Team','One row per person. Adding an email invites them.',team),scr('Links','Website first. Marks show which we are sure of.',links),scr('Verify ownership','One button to Google. Three reassurances.',verify)]])
