kb=f'<div class="kbar"><span class="av bl" style="width: 36px; height: 36px; font-size: 12px;">KM</span><span style="flex: 1; display: flex; flex-direction: column; line-height: 17px;"><b style="font-size: 14px;">Go through it with Kody</b><span class="xs">Your representative · 30 min</span></span><a class="bp sm" href="#" style="height: 38px; font-size: 13px; padding: 0 14px;">Book</a></div>'
def aud(i,body,btn='Next'):
    dots=''.join(f'<i class="{"on" if k<=i else ""}"></i>' for k in range(6))
    return appbar(f'<a class="icb" href="#">{ic(I["x"])}</a>','<span class="sm" style="font-weight: 600;">Free AI audit · Lumen</span>','<span style="width: 44px;"></span>',True)+kb+f'<div class="stp" style="padding: 0 20px 4px;">{dots}</div><div class="bd" style="gap: 14px; padding-top: 12px;">{body}</div><div class="cta" style="flex-direction: row; align-items: center; justify-content: space-between;"><span class="sm" style="font-weight: 600; {"visibility: hidden;" if i==0 else ""}">‹ Back</span><a class="bp" href="#" style="padding: 0 30px;">{btn} ⟶</a></div>'
def ln(t,s): return f'<span style="display: flex; gap: 10px; align-items: center; font-size: 15px; {"color: #8a93a3;" if s=="q" else ""}"><span style="width: 22px; height: 22px; border-radius: 50%; flex-shrink: 0; display: flex; align-items: center; justify-content: center; font-size: 12px; {"background: #237233; color: #fff;" if s=="d" else ("border: 2px solid #13203a; box-sizing: border-box;" if s=="r" else "border: 1.5px solid #c9c3b6; box-sizing: border-box;")}">{"✓" if s=="d" else ""}</span>{t}</span>'
a0=aud(0,'<span class="ey">Running your audit</span><h1 class="T">Checking what AI says about <em>Lumen</em>.</h1><span class="sm mu" style="margin-top: -6px;">About 2 minutes.</span><div style="height: 8px; border-radius: 4px; background: #e4ded2; overflow: hidden;"><div style="width: 62%; height: 100%; background: #2b59d9;"></div></div>'+ln('Asked ChatGPT 40 questions','d')+ln('Asked Gemini the same 40','d')+ln('Asking Claude, 26 of 40','r')+ln('Reading 612 reviews','q')+ln('Checking 31 directories','q')+ln('Finding who AI names instead','q'),'Show me')
a1=aud(1,'<span class="ey">What AI says</span><h1 class="T">AI mentions you in <em>38%</em> of answers.</h1><div style="display: grid; grid-template-columns: 1fr 1fr; gap: 10px;"><div class="cd" style="gap: 0;"><span class="big" style="color: #c13515;">58</span><span class="xs mu">AI Score. Irvine average 71</span></div><div class="cd" style="gap: 0;"><span class="big">3/8</span><span class="xs mu">top questions where ChatGPT names you</span></div></div><div class="cd" style="gap: 6px;"><span class="ey">Asked ChatGPT, Oct 1</span><b style="font-size: 15px;">"Best med spa for natural lip filler in Irvine?"</b><span class="sm mu">"Coastline Med Spa and Glow Bar are popular choices..."</span><span class="sm" style="color: #c13515; font-weight: 700;">Lumen not mentioned.</span></div>')
a2=aud(2,'<span class="ey">What AI gets wrong</span><h1 class="T">AI has <em>3 facts</em> wrong.</h1>'+''.join(f'<div class="cd" style="gap: 4px; padding: 12px 14px;"><span class="ey">{k}</span><span style="color: #c13515; text-decoration: line-through;">{w}</span><span style="color: #1c5f2a; font-weight: 700;">{r}</span></div>' for k,w,r in [('Mondays','Open 9 to 6','Closed'),('Who injects','Licensed aestheticians','Dr. Nair or a nurse injector'),('Consult','Free','$75, credited if you book')]))
SRC='<svg viewBox="0 0 350 230" width="100%" aria-hidden="true" font-family="Figtree,sans-serif">'+''.join(f'<rect x="4" y="{6+i*44}" width="150" height="32" rx="6" fill="{c}" stroke="{s}"/><text x="14" y="{27+i*44}" font-size="12" fill="#13203a">{t}</text><path d="M154 {22+i*44} C 230 {22+i*44}, 230 115, 272 115" fill="none" stroke="{s}" stroke-width="{w}" {d}/>' for i,(t,c,s,w,d) in enumerate([('Yelp: open Mondays','#fdecea','#c13515','1.4','stroke-dasharray="4 4"'),('Old site: 9 to 8','#fdecea','#c13515','1.4','stroke-dasharray="4 4"'),('Google: aestheticians','#fdecea','#c13515','1.4','stroke-dasharray="4 4"'),('Directory: old phone','#fdecea','#c13515','1.4','stroke-dasharray="4 4"'),('Your record: correct','#eaf5ec','#237233','3','')]))+'<circle cx="308" cy="115" r="36" fill="#13203a"/><text x="308" y="120" font-size="14" fill="#fff" text-anchor="middle" font-weight="700">AI</text></svg>'
a3=aud(3,'<span class="ey">Why fixing it here is not enough</span><h1 class="T" style="font-size: 34px; line-height: 36px;">You fixed it. <em>AI has not noticed yet.</em></h1><span class="sm mu">AI reads dozens of sources. Most still have the old info.</span><div class="cd">'+SRC+'</div>')
a4=aud(4,'<span class="ey">Who AI recommends instead</span><h1 class="T">AI sends people to <em>Coastline</em>.</h1><div class="cd" style="gap: 12px;">'+''.join(f'<div style="display: flex; flex-direction: column; gap: 4px;"><span style="display: flex; justify-content: space-between;" class="sm"><b style="{"color: #c13515;" if n=="Lumen" else ""}">{n}</b><b>{p}%</b></span><div style="height: 14px; border-radius: 7px; background: #ece6da;"><div style="width: {p}%; height: 100%; border-radius: 7px; background: {c};"></div></div></div>' for n,p,c in [('Coastline Med Spa',78,'#13203a'),('Glow Bar Irvine',61,'#5b6474'),('Spectrum Aesthetics',44,'#8a93a3'),('Lumen',38,'#e5482d')])+'<span class="xs mu">Share of AI answers, med spas in Irvine</span></div>')
def pl(n,p,d,sc,hot=False): return f'<div class="cd" style="padding: 12px 14px; gap: 2px; {"border: 2px solid #13203a; background: #fbf4ea;" if hot else ""}"><span style="display: flex; justify-content: space-between; align-items: baseline;"><b>{n}</b><span class="T2" style="font-size: 24px;">{p}<span class="xs mu" style="font-family: Figtree, sans-serif;">/mo</span></span></span><span class="xs mu">{d}</span><span class="xs" style="font-weight: 700; color: #237233;">AI Score about {sc} by March</span></div>'
a5=aud(5,'<span class="ey">How we fix it</span><h1 class="T" style="font-size: 32px; line-height: 34px;">Make the sources agree. Get <em>recommended</em>.</h1>'+pl('Fix','$500','Your correct info on a new directory every day.',63)+pl('Trust','$1,500','Plus reviews, answers, press releases, Google posts.',72,True)+pl('Authority','$3,000','Plus your website, articles and your story.',80)+'<span class="lk" style="font-size: 14px;">See the full report</span>','Start Trust')
ks=f'''<div class="bd np" style="position: relative;"><div style="opacity: 0.5;">{a2.split('<div class="cta"')[0]}</div><div class="scrim"></div><div class="sh"><span class="gr"></span><div style="display: flex; gap: 12px; align-items: center;">{WAVE}<span style="display: flex; flex-direction: column;"><b style="font-size: 19px;">Book with Kody</b><span class="sm mu">Kody Muffoletto, your representative</span></span></div><span class="lb">Thursday, Oct 1 · Pacific</span><div style="display: grid; grid-template-columns: 1fr 1fr; gap: 8px;">{"".join(f'<span class="ch" style="height: 48px; justify-content: center; {"background: #13203a; color: #fff; border-color: #13203a;" if t=="10:30 AM" else ""}">{t}</span>' for t in ["9:00 AM","10:30 AM","1:00 PM","3:30 PM"])}</div><a class="bp" href="#">Book Thursday, 10:30 AM</a><span class="sm mu" style="text-align: center;">Rather write? <a class="lk" href="#" style="font-size: 14px;">support@localairegistry.com</a></span></div></div>'''
board('MAudit.dc.html','M6 · Mobile: free AI audit','Mobile · Free AI audit','The desktop left panel becomes a Kody bar pinned under the header on every slide. Tapping Book opens a sheet with times. Six slides, one idea each, then plans.',
 [[scr('1 · Running','Progress while it runs. Kody is already there.',a0),scr('2 · What AI says','Two numbers and one real answer.',a1),scr('3 · What is wrong','Wrong crossed out in red, right in green.',a2),scr('4 · Why fixing is not enough','The sources drawing, sized for a phone.',a3)],
  [scr('5 · Who wins instead','Simple bars, you in red.',a4),scr('6 · How we fix it','Three plans stacked. Trust pre-picked.',a5),scr('Book with Kody','A sheet over any slide. Four big time buttons.',ks)]])
