def mrow(k,t,s='',h='#'): return f'<a class="rw" href="{h}"><span class="av bl" style="border-radius: 10px; width: 38px; height: 38px;">{ic(I[k],20)}</span><span class="g"><b>{t}</b>{f"<span>{s}</span>" if s else ""}</span>{ic(I["chev"],18)}</a>'
more=appbar('','More','',True)+f'''<div class="bd" style="gap: 12px;"><div style="display: flex; gap: 12px; align-items: center;"><span class="av" style="width: 52px; height: 52px;">PN</span><span style="display: flex; flex-direction: column;"><b style="font-size: 18px;">Dr. Priya Nair</b><span class="sm mu">Owner · Lumen Aesthetics</span></span></div>
<a class="cd pe" href="#" style="gap: 2px; padding: 14px 16px;"><span class="T2" style="font-size: 22px;">Refer a business, pay less</span><span class="sm">15% off your plan for each one, forever. Stack them until it is free.</span></a>
<div>{mrow("team","Team","Yours and ours")}{mrow("card","Plan and billing","Trust · $1,500/mo")}{mrow("note","AI notes")}{mrow("gear","Settings")}{mrow("help","Help center")}{mrow("share","View my public page","","MProfile.dc.html")}</div><span class="lk mu" style="font-size: 15px;">Sign out</span></div>'''+tabbar('own','More',{'Inbox':'3','Premium':'5'})
def tm(a,n,r,tg): return f'<div style="padding: 12px 0; border-bottom: 1px solid #ece6da; display: flex; flex-direction: column; gap: 8px;"><div style="display: flex; gap: 12px; align-items: center;"><span class="av lt">{a}</span><span style="flex: 1; display: flex; flex-direction: column;"><b style="font-size: 16px;">{n}</b></span><span class="ch" style="height: 34px; font-size: 13px;">{r} ▾</span></div><div style="display: flex; gap: 6px; flex-wrap: wrap; padding-left: 52px;">{"".join(f"<span class=\'pill {"n" if v else "l"}\' style=\'height: 24px; font-size: 11px;\'>{l}</span>" for v,l in zip(tg,["Approvals","Reports","Billing"]))}</div></div>'
team=bk('Team')+f'''<div class="chs" style="padding: 0 16px;"><span class="ch on">Your team</span><span class="ch">Our team</span></div><div class="bd" style="gap: 10px; padding-top: 10px;"><div>{tm("PN","Dr. Priya Nair","Owner",[1,1,1])}{tm("MO","Maya Ortiz","Front desk",[0,0,0])}{tm("NR","Nadia Rahimi, RN","Member",[0,0,0])}</div><div class="cd nv" style="gap: 8px;"><span class="T2" style="font-size: 22px; line-height: 25px;">Add someone who can approve when you cannot.</span><div class="inp" style="height: 48px; color: #8a93a3;">name@lumenirvine.com</div><span class="bp o sm">Send invite</span></div></div>'''
def us(a,r,n,e): return f'<div class="rw" style="align-items: flex-start; padding: 12px 0;"><span class="av">{a}</span><span class="g"><span class="xs" style="font-weight: 700; letter-spacing: 0.1em; color: #2b59d9; text-transform: uppercase;">{r}</span><b>{n}</b><span>{e}</span></span><a class="icb" href="#">{ic(I["mail"],20)}</a></div>'
ours=bk('Team')+f'''<div class="chs" style="padding: 0 16px;"><span class="ch">Your team</span><span class="ch on">Our team</span></div><div class="bd" style="gap: 0; padding-top: 6px;">{us("KM","Your rep","Kody Muffoletto","Anything. Start here.")}{us("C","Onboarding","Caron","Setup and results")}{us("ES","Support","Eric Sim","Billing and account")}{us("CA","Technical","Clinton Adeleke","Something is broken")}{us("BD","Partnerships","Bridgette DeBrino","Multi-location, referrals")}{us("SL","Strategy","Steve Lee","How AI sees you")}</div>'''
ref=bk('')+f'''<div class="bd" style="gap: 14px;"><span class="ey">Referral program</span><h1 class="T" style="font-size: 40px; line-height: 42px;">Refer a business. Pay <em>less</em>, forever.</h1><p class="mu" style="margin: 0;">Every business you refer that starts a plan takes 15% off your bill for as long as they stay. It stacks until your plan is free.</p><div style="display: grid; grid-template-columns: repeat(3,1fr); gap: 8px;">{"".join(f'<div class="cd pe" style="padding: 10px; gap: 0; align-items: center;"><b style="font-size: 20px;">{a}</b><span class="xs">{b}</span></div>' for a,b in [("1","15% off"),("3","45% off"),("7","free")])}</div><div class="inp" style="justify-content: space-between; font-size: 15px;">localairegistry.com/r/lumen-priya<b class="sm">Copy</b></div></div><div class="cta"><a class="bp" href="#">Book a call to refer someone</a></div>'''
def st(t,s,on=None): return f'<div class="rw"><span class="g"><b>{t}</b><span>{s}</span></span>{f"<span class=\'sw {"on" if on else ""}\'></span>" if on is not None else ic(I["chev"],18)}</div>'
sett=bk('Settings')+f'''<div class="bd" style="gap: 8px;"><span class="ey">Business</span><div>{st("Locations","1 location · Irvine Spectrum")}{st("Connected accounts","Google, Instagram")}</div><span class="ey" style="margin-top: 8px;">Notifications</span><div>{st("New questions","Text and email",True)}{st("Booking requests","Text",True)}{st("Weekly summary","Email, Mondays",False)}</div><span class="ey" style="margin-top: 8px;">Account</span><div>{st("Sign-in and security","Text code to (949) 555-0148")}{st("Delete account","")}</div></div>'''
helpc=bk('Help center')+f'''<div class="bd" style="gap: 12px;"><div class="srch">{ic(I["search"],20)}Search help</div><div>{"".join(mrow(k,t,s) for k,t,s in [("check","Verifying ownership","4 articles"),("pencil","Editing your page","6 articles"),("cal","How Premium works","5 articles"),("card","Billing and plans","4 articles")])}</div><div class="kbar" style="margin: 0;">{WAVE.replace('width="56" height="56"','width="40" height="40"')}<span style="flex: 1;" class="sm"><b>Still stuck?</b><br><span class="mu">Kody answers in minutes.</span></span><a class="bp sm" href="#" style="height: 38px; font-size: 13px; padding: 0 14px;">Book</a></div></div>'''
def pp(n,p,d,sel=False): return f'<div class="cd" style="padding: 14px 16px; gap: 2px; {"border: 2px solid #13203a; background: #fbf4ea;" if sel else ""}"><span style="display: flex; justify-content: space-between; align-items: baseline;"><b style="font-size: 17px; display: flex; align-items: center; gap: 8px;"><span style="width: 20px; height: 20px; border-radius: 50%; border: 2px solid {"#13203a" if sel else "#cfc8ba"}; box-sizing: border-box; {"background: radial-gradient(#13203a 45%, transparent 50%);" if sel else ""}"></span>{n}</b><span class="T2" style="font-size: 24px;">{p}</span></span><span class="sm mu" style="padding-left: 28px;">{d}</span></div>'
plans=bk('Pick a plan')+f'''<div class="bd" style="gap: 10px;">{pp("Free","$0","Claim, fix your info, answer locals.")}{pp("Fix","$500/mo","12 pieces a month. Directories every day.")}{pp("Trust","$1,500/mo","38 pieces a month. Reviews, press, Google posts.",True)}{pp("Authority","$3,000/mo","69 pieces a month. Website and articles too.")}<span class="xs mu" style="text-align: center;">No contract. Cancel any time.</span></div><div class="cta"><a class="bp" href="#">Continue with Trust</a></div>'''
chk=bk('Checkout')+f'''<div class="bd" style="gap: 14px;"><div class="cd" style="gap: 0; padding: 4px 16px;"><div class="fr"><span class="k">Plan</span><span class="v">Trust</span></div><div class="fr"><span class="k">Billed</span><span class="v">Monthly</span></div><div class="fr"><span class="k">Today</span><span class="v">$1,500</span></div></div><span class="lb">Card</span><div class="inp f">4242 4242 4242 4242</div><div style="display: grid; grid-template-columns: 1fr 1fr; gap: 10px;"><div class="inp">10 / 28</div><div class="inp">CVC</div></div><div class="inp">ZIP 92618</div><span class="xs mu" style="display: flex; gap: 6px; align-items: center;">{ic(I["lock"],14)} Secure. Cancel any time from Plan and billing.</span></div><div class="cta"><a class="bp" href="#">Pay $1,500 and start</a></div>'''
bill=bk('Plan and billing')+f'''<div class="bd" style="gap: 12px;"><div class="cd" style="gap: 4px;"><span class="ey">Your plan</span><span style="display: flex; justify-content: space-between; align-items: baseline;"><span class="T2">Trust</span><b>$1,500/mo</b></span><span class="sm mu">Next bill Nov 1, 2026 · Visa ending 4242</span><div style="display: grid; grid-template-columns: 1fr 1fr; gap: 8px; margin-top: 8px;"><span class="bp sm">Change plan</span><span class="bp sm o">Update card</span></div></div><span class="ey">Invoices</span><div>{"".join(f'<div class="fr"><span class="sm">{d}</span><span class="v" style="font-weight: 500;">$1,500 <span class="lk" style="font-size: 13px; margin-left: 8px;">PDF</span></span></div>' for d in ["Oct 1, 2026","Sep 1, 2026","Aug 1, 2026"])}</div><span class="lk mu" style="font-size: 14px;">Cancel plan</span></div>'''
notes=bk('AI notes')+f'''<div class="bd" style="gap: 10px;"><span class="sm mu">Tell AI things that are true about Lumen. We add them to your record.</span>{"".join(f'<div class="cd" style="gap: 4px; padding: 12px 14px;"><span class="sm">{t}</span><span class="xs mu">{w}</span></div>' for t,w in [("We never upsell a second syringe at the first visit.","Added Sep 20 · live on ChatGPT"),("Dr. Nair trained at UCLA and does every lip filler herself.","Added Sep 18 · live"),("Spanish and Farsi spoken at the front desk.","Added Sep 12 · going out")])}</div><div class="cta"><div class="inp" style="height: 50px; color: #8a93a3;">Add a note for AI</div></div>'''
board('MAccount.dc.html','M8 · Mobile: account, plans and billing','Mobile · Account, plans and billing','Everything that is not daily work lives under More. Plans are radio cards with one button. Checkout is one screen.',
 [[scr('More','Referral card first, then everything else as a list.',more),scr('Team, yours','Role picker and what each person gets, per person.',team),scr('Team, ours','Who to reach for what, one tap to email.',ours),scr('Referral','How it stacks, your link, one button.',ref),scr('Settings','Grouped rows. Toggles for alerts.',sett)],
  [scr('Help center','Search, topics, then Kody.',helpc),scr('Pick a plan','Radio cards. Price on the right.',plans),scr('Checkout','Summary, card, pay.',chk),scr('Plan and billing','Plan, two actions, invoices.',bill),scr('AI notes','Facts you tell AI, and where each is live.',notes)]])
