import sys; sys.path.insert(0,'/tmp/gen')
src=open('/tmp/gen/stories2.py').read(); exec(src[:src.index('# ---- POST')])
fa=flow('Edit a fact on My business','Turn on Edit and every fact gets a pencil. What you save is confirmed by you, the owner, and logged in the public change history.',[
frame('1','Turn on Edit','''<div style="display: flex; justify-content: space-between; align-items: center;"><strong style="font-size: 16px;">Lumen Aesthetics</strong><span class="btn b-sm b-dark">✎ Edit</span></div><div class="row"><span class="k">Hours</span><span><span class="mk mk-ai"></span>Mon to Sat, 9 to 8 <span class="pen hov"></span></span></div><div class="row"><span class="k">Phone</span><span><span class="mk mk-site"></span>(949) 555-0148 <span class="pen"></span></span></div><div class="row"><span class="k">Parking</span><span><span class="mk mk-vis"></span>Structure B, level 3 <span class="pen"></span></span></div><div class="row"><span class="k">Known for</span><span><span class="mk mk-site"></span>Lip filler, Botox, Morpheus8 <span class="pen"></span></span></div>'''),
frame('2','Click the pencil','''<div class="mh"><strong>Hours</strong><span class="x">✕</span></div><div class="note"><span class="mk mk-ai"></span><strong>AI guess:</strong> Mon to Sat, 9 AM to 8 PM. Gemini and Claude say this. Nobody has confirmed it.</div><div class="row"><span class="k">Monday</span><span class="inp focus" style="height: 36px;">Closed</span></div><div class="row"><span class="k">Tue to Fri</span><span class="inp" style="height: 36px;">9 AM to 6 PM</span></div><div class="row"><span class="k">Saturday</span><span class="inp" style="height: 36px;">9 AM to 4 PM</span></div><span class="btn b-dark" style="margin-top: auto;">Save</span>'''),
frame('3','Saved and tracked','''<div class="row"><span class="k">Hours</span><span><span class="mk mk-site"></span><strong>Closed Mon · Tue to Fri 9 to 6 · Sat 9 to 4</strong></span></div><span class="old">Mon to Sat, 9 to 8</span><div class="okb">Confirmed by you, just now. Added to the <a href="History.dc.html">change history</a>.</div><div class="push"><span>Google, Yelp and 4 more still say open Monday.</span><a href="OwnerPremium.dc.html" class="btn b-sm b-coral">Push it to AI</a></div>''')])
fb=flow('Confirm what AI guessed and what visitors suggested','From the dashboard tile "9 facts need you to confirm." One card at a time.',[
frame('4','The review list','''<div class="mh"><strong>9 facts need you</strong><span class="x">✕</span></div><div class="chips"><span class="chip on">All 9</span><span class="chip">6 AI guesses</span><span class="chip">3 from visitors</span></div><div class="lst"><div class="it"><span><span class="mk mk-ai"></span>Takes HSA cards</span><span class="mu">AI guess</span></div><div class="it"><span><span class="mk mk-vis"></span>Closed Sat, Oct 3</span><span class="mu">kellyw_irvine</span></div><div class="it"><span><span class="mk mk-ai"></span>Injections by aestheticians</span><span class="mu">AI guess</span></div><div class="it"><span><span class="mk mk-vis"></span>Free parking, level 3</span><span class="mu">3 locals</span></div></div>'''),
frame('5','An AI guess','''<span class="tg" style="align-self: flex-start;">AI guess · 2 of 9</span><strong style="font-size: 17px;">"Injections are done by licensed aestheticians."</strong><span class="mu" style="font-size: 13px;">Gemini says this. Claude and ChatGPT don't.</span><div class="opt"><span class="rdo"></span>That's right, confirm it</div><div class="opt on"><span class="rdo"></span><span><strong>Fix it</strong><br><span class="inp" style="margin-top: 6px; height: 38px;">Dr. Nair or a nurse injector does every injection</span></span></div><div class="opt"><span class="rdo"></span>Not us, remove it</div><span class="btn b-dark" style="margin-top: auto;">Save and next</span>'''),
frame('6','A visitor suggestion','''<span class="tg" style="align-self: flex-start;">From a visitor · 3 of 9</span><strong style="font-size: 17px;">Closed Saturday, Oct 3</strong><div class="note"><strong>kellyw_irvine</strong> · called on Sep 21 · 14 posts, 3 fixes accepted</div><span style="display: flex; gap: 8px;"><span class="btn b-dark" style="flex: 1;">Accept</span><span class="btn" style="flex: 1;">Not right</span></span><span class="mu" style="font-size: 12px;">Accepting makes it a confirmed fact and gives Kelly credit. Her first accepted fix earns her the Local expert badge.</span>'''),
frame('7','Accepted','''<div class="row"><span class="k">Oct 3</span><span><span class="mk mk-site"></span><strong>Closed</strong></span></div><div class="okb">Confirmed by you, suggested by kellyw_irvine. She just got a note that you accepted it.</div><div class="note">Not right instead? Tell us why, privately: "We're open, training is Oct 10." The suggestion comes off the page.</div>'''),
frame('8','All done','''<div class="big"><span class="ic" style="background: #e8f5ea; color: #237233;">✓</span><strong style="font-size: 20px;">All 9 confirmed</strong><span style="font-size: 14px; line-height: 21px; color: #3d4658;">Every fact on Lumen's page now has a solid mark. Confirmed facts are what AI repeats.</span></div><div class="lst"><div class="it"><span>AI guesses left</span><b>0</b></div><div class="it"><span>Visitor suggestions accepted</span><b>2 of 3</b></div><div class="it"><span>Expected AI Score change</span><b style="color: #237233;">+2</b></div></div><a href="Dashboard.dc.html" class="btn">Back to my business</a>''')],5)
B=header('<a href="Dashboard.dc.html" class="btn b-sm">Back to my business</a>')+f'<div class="wrap">{fa}{fb}</div>'
open(P+'Edit.dc.html','w').write(page('How editing works',CSS2,B,'    return {};')); print('ok')
