import re
LOGO='<svg width="28" height="28" viewBox="0 0 30 30" fill="none" aria-hidden="true"><path d="M15 3 27.5 27h-8.2L15 18.6 10.7 27H2.5L15 3Z" fill="#2b59d9"></path><path d="M15 18.6 19.3 27h-8.6L15 18.6Z" fill="#e5482d"></path></svg>'
HS='height: 68px; flex-shrink: 0; box-sizing: border-box; padding: 0 40px; background: #f3efe7; border-bottom: 1px solid #e4ded2; display: flex; align-items: center; gap: 24px;'
def logo(href='Home.dc.html'): return f'<a href="{href}" style="display: flex; align-items: center; gap: 10px; text-decoration: none; flex-shrink: 0;">{LOGO}<span style="font-weight: 700; font-size: 16px; color: #13203a;">Local AI Registry</span></a>'
L='font-size: 14px; font-weight: 600; color: #3d4658; text-decoration: none; padding: 8px 10px;'
LON='font-size: 14px; font-weight: 700; color: #13203a; text-decoration: none; padding: 8px 10px; box-shadow: inset 0 -2px 0 #13203a;'
BTN='display: inline-flex; align-items: center; height: 38px; padding: 0 16px; border-radius: 19px; font-size: 14px; font-weight: 700; text-decoration: none; margin-left: 8px;'
def pub(active='', cta=('Join','Join.dc.html'), middle=''):
    nav=''.join(f'<a href="{h}" style="{LON if k==active else L}">{t}</a>' for k,t,h in [('explore','Explore','Explore.dc.html'),('biz','For business','Business.dc.html')])
    return f'<header style="{HS}">{logo()}{middle}<span style="margin-left: auto; display: flex; align-items: center;">{nav}<a href="SignIn.dc.html" style="{L}">Sign in</a><a href="{cta[1]}" style="{BTN} background: #13203a; color: #ffffff;">{cta[0]}</a></span></header>'
def cons(active=''):
    nav=''.join(f'<a href="{h}" style="{LON if k==active else L}">{t}</a>' for k,t,h in [('explore','Explore','ExploreMe.dc.html'),('biz','For business','Business.dc.html')])
    return f'<header style="{HS}">{logo("ExploreMe.dc.html")}<span style="margin-left: auto; display: flex; align-items: center; gap: 4px;">{nav}<a href="Post.dc.html" style="{BTN} background: #e5482d; color: #ffffff;">Post</a><span style="margin-left: 10px; font-size: 18px;">🔔</span><a href="Me.dc.html" style="margin-left: 10px; width: 34px; height: 34px; border-radius: 50%; background: #dfe8f5; color: #13203a; display: flex; align-items: center; justify-content: center; font-size: 13px; font-weight: 700; text-decoration: none;">W</a></span></header>'
IC={'home':'<path d="M4 11 12 4l8 7v9h-5v-6H9v6H4z"/>','page':'<path d="M4 9h16l-1.5-4h-13z"/><path d="M5 9v11h14V9"/><path d="M10 20v-6h4v6"/>','inbox':'<path d="M3 13h5l2 3h4l2-3h5"/><path d="M5 5h14l2 8v6H3v-6z"/>','work':'<rect x="4" y="5" width="16" height="15" rx="2"/><path d="M4 10h16M9 3v4M15 3v4"/><path d="m9 15 2 2 4-4"/>'}
def owner(active=''):
    items=[('home','Dashboard','OwnerHome.dc.html'),('page','My business','Dashboard.dc.html'),('inbox','Inbox','OwnerInbox.dc.html'),('work','Premium','OwnerPremium.dc.html')]
    nav=''.join(f'<a href="{h}" style="display: inline-flex; flex-direction: column; align-items: center; justify-content: center; gap: 3px; height: 68px; padding: 0 16px; box-sizing: border-box; font-size: 12px; font-weight: {700 if k==active else 600}; color: {"#13203a" if k==active else "#667085"}; text-decoration: none; border-bottom: 2px solid {"#13203a" if k==active else "transparent"};"><svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">{IC[k]}</svg>{t}</a>' for k,t,h in items)
    chip='<span style="display: flex; align-items: center; gap: 10px; height: 44px; padding: 0 12px 0 6px; border: 1px solid #e4ded2; border-radius: 12px; background: #ffffff; flex-shrink: 0;"><span style="width: 30px; height: 30px; border-radius: 8px; background: #13203a; color: #ffffff; display: flex; align-items: center; justify-content: center; font-size: 13px; font-weight: 700;">L</span><span style="display: flex; flex-direction: column; line-height: 16px;"><strong style="font-size: 13px; color: #13203a;">Lumen Aesthetics</strong><span style="font-size: 11px; color: #667085;">Irvine Spectrum</span></span><span style="font-size: 9px; color: #667085;">▾</span></span>'
    return f'<header style="{HS} gap: 18px;">{logo("OwnerHome.dc.html")}{chip}<nav style="display: flex; align-items: center;">{nav}</nav><span style="margin-left: auto; display: flex; align-items: center; gap: 14px;"><a href="Upgrade.dc.html" style="height: 38px; padding: 0 18px; border-radius: 9999px; background: #13203a; color: #ffffff; display: inline-flex; align-items: center; font-size: 14px; font-weight: 600; text-decoration: none;">See plans</a><span style="font-size: 18px;">🔔</span><span style="width: 34px; height: 34px; border-radius: 50%; background: #e4ded2; color: #13203a; display: flex; align-items: center; justify-content: center; font-size: 13px; font-weight: 700;">PN</span></span></header>'
def help_():
    return '<span style="display: flex; align-items: center; gap: 14px; justify-content: flex-end; font-size: 13px;"><a href="#" style="display: inline-flex; align-items: center; gap: 8px; height: 36px; padding: 0 14px 0 4px; border-radius: 9999px; border: 1px solid #13203a; color: #13203a; text-decoration: none; font-weight: 600;"><span style="width: 28px; height: 28px; border-radius: 50%; background: #dfe8f5; display: flex; align-items: center; justify-content: center; font-size: 11px; font-weight: 700;">KM</span>Book with Kody Muffoletto</a><span style="color: #8a93a3;">or</span><a href="mailto:support@localairegistry.com" style="color: #3d4658; font-weight: 600; text-decoration: none;">Contact support</a></span>'
def flowh(steps,cur):
    parts=[]
    for i,t in enumerate(steps,1):
        done=i<cur; on=i==cur
        dot=f'<span style="width: 22px; height: 22px; border-radius: 50%; display: inline-flex; align-items: center; justify-content: center; font-size: 11px; font-weight: 700; background: {"#237233" if done else ("#13203a" if on else "#e4ded2")}; color: {"#ffffff" if (done or on) else "#667085"};">{"✓" if done else i}</span>'
        parts.append(f'<span style="display: inline-flex; align-items: center; gap: 8px; font-size: 13px; font-weight: 600; color: {"#13203a" if (done or on) else "#8a8a8a"}; white-space: nowrap;">{dot}{t}</span>')
    st='<span style="width: 24px; height: 1px; background: #dcd5c7;"></span>'.join(parts)
    return f'<header style="{HS} display: grid; grid-template-columns: 1fr auto 1fr;">{logo()}<span style="display: flex; align-items: center; gap: 10px;">{st}</span>{help_()}</header>'
def doc(label,back,href):
    return f'<header style="{HS}">{logo()}<span style="height: 24px; padding: 0 10px; border-radius: 12px; background: #e9e3d6; color: #5b6474; font-size: 11px; font-weight: 700; letter-spacing: 0.08em; text-transform: uppercase; display: inline-flex; align-items: center;">Storyboard · {label}</span><a href="{href}" style="margin-left: auto; font-size: 14px; font-weight: 600; color: #13203a; text-decoration: none;">‹ {back}</a></header>'
def swap(s,new):
    i=s.index('<header'); j=s.index('</header>',i)+9
    return s[:i]+new+s[j:]
