import sys; sys.path.insert(0,'/tmp/gen'); from common import *
TRI="url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='22' height='22' viewBox='0 0 22 22'%3E%3Cpath d='M11 3.5L19.5 18.5H2.5Z' fill='none' stroke='%238a8a8a' stroke-width='2.4' stroke-linejoin='round'/%3E%3C/svg%3E\") center / 100% 100% no-repeat"
CSS='''.mk{position:relative;display:inline-block;width:11px;height:11px;margin:0 0 2px 5px;vertical-align:middle}
.mk::after{content:"";position:absolute;inset:0}
.mk-site::after{inset:2px;background:#008a05;border-radius:50%}
.mk-vis::after{inset:2px;border:1.6px solid #e8740c;border-radius:50%}
.mk-ai::after{inset:0;background:'''+TRI+'''}
.ask{display:flex;align-items:center;gap:10px;height:64px;padding:0 10px 0 22px;border:1px solid #dddddd;border-radius:32px;box-shadow:0 6px 24px rgba(0,0,0,0.08);background:#ffffff}
.ask input{flex-grow:1;border:none;outline:none;font-family:inherit;font-size:17px;color:#222222;background:transparent}
.chip{display:inline-flex;align-items:center;height:34px;padding:0 14px;border:1px solid #dddddd;border-radius:17px;font-size:13px;cursor:pointer;background:#ffffff;white-space:nowrap}
.chip.on{border:2px solid #222222;padding:0 13px;font-weight:600}
.ans{border:1px solid #dddddd;border-radius:16px;padding:22px 24px;display:flex;flex-direction:column;gap:12px;background:#ffffff}
.ans p{margin:0;font-size:16px;line-height:25px}
.cite{display:inline-flex;align-items:center;justify-content:center;min-width:18px;height:18px;padding:0 4px;border-radius:9px;background:#f0f0f0;font-size:11px;font-weight:700;color:#484848;vertical-align:2px;margin-left:2px}
.res{display:grid;grid-template-columns:1fr 520px;gap:24px;align-items:start}
.bc{display:grid;grid-template-columns:132px 1fr;gap:14px;padding:14px;border:1px solid #ebebeb;border-radius:14px;text-decoration:none;color:#222222;background:#ffffff}
.bc:hover{box-shadow:0 6px 20px rgba(0,0,0,0.08)}
.bph{height:112px;border-radius:10px;display:flex;align-items:flex-end;padding:6px;box-sizing:border-box;font-size:10px;font-weight:600;color:#333333}
.sc{display:inline-flex;align-items:center;height:22px;padding:0 8px;border-radius:11px;font-size:12px;font-weight:700}
.map{position:sticky;top:20px;height:640px;border-radius:16px;overflow:hidden;background:#e8ece6;border:1px solid #dddddd}
.map .road{position:absolute;background:#ffffff}
.pin{position:absolute;transform:translate(-50%,-100%);display:flex;align-items:center;gap:4px;height:30px;padding:0 10px;border-radius:15px;background:#ffffff;box-shadow:0 2px 8px rgba(0,0,0,0.18);font-size:13px;font-weight:700;white-space:nowrap}
.pin.on{background:#222222;color:#ffffff}
.rail{display:flex;gap:12px;flex-wrap:wrap}
.rc{display:flex;flex-direction:column;gap:2px;padding:14px 16px;border:1px solid #ebebeb;border-radius:12px;min-width:150px;text-decoration:none;color:#222222}
.news{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}
.nw{padding:14px 16px;border:1px solid #ebebeb;border-radius:12px;display:flex;flex-direction:column;gap:6px;font-size:13px;line-height:19px}
'''
BODY=header('<a href="Main.dc.html" class="btn b-sm" style="border-color: transparent;">Explore</a><a href="Claim.dc.html" class="btn b-sm" style="border-color: #dddddd;">For businesses</a><a href="#" class="btn b-sm" style="border-color: transparent;">Sign in</a>')+'''
<div style="padding: 56px 120px 24px; display: flex; flex-direction: column; align-items: center; gap: 18px; background: linear-gradient(180deg, #fff5f7 0%, #ffffff 100%);">
<span class="mu" style="font-size: 13px; font-weight: 600;">12,400 local businesses. Every fact marked and sourced.</span>
<h1 style="margin: 0; font-size: 44px; line-height: 50px; font-weight: 700; letter-spacing: -0.02em; text-align: center; max-width: 820px;">Ask anything about the businesses near you</h1>
<span style="font-size: 17px; line-height: 25px; color: #484848; text-align: center; max-width: 680px;">Answers come from verified records, not ads. You see what is confirmed, what visitors said, and what AI is only guessing.</span>
<div class="ask" style="width: 820px;"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#222222" stroke-width="2.2" stroke-linecap="round" aria-hidden="true"><circle cx="11" cy="11" r="7"></circle><path d="M20 20l-4-4"></path></svg><input type="text" value="{{q.q}}" aria-label="Ask"><span class="mu" style="font-size: 13px; white-space: nowrap;">Irvine, CA</span><a href="#" class="btn b-coral" style="height: 46px; border-radius: 23px; padding: 0 24px;">Ask</a></div>
<div style="display: flex; gap: 8px; flex-wrap: wrap; justify-content: center;"><sc-for list="{{chips}}" as="c" hint-placeholder-count="3"><span class="chip {{c.on}}" onClick="{{c.pick}}">{{c.t}}</span></sc-for></div>
</div>
<div style="padding: 12px 120px 48px; display: flex; flex-direction: column; gap: 28px;">
<div class="ans"><div style="display: flex; align-items: center; justify-content: space-between;"><span style="display: flex; align-items: center; gap: 8px;"><strong style="font-size: 15px;">Answer</strong><span class="mu" style="font-size: 13px;">from {{q.src}} sourced facts, checked this morning</span></span><span style="display: flex; gap: 14px; font-size: 12px; color: #6a6a6a;"><span><span class="mk mk-site" style="margin: 0 4px 2px 0;"></span>Confirmed</span><span><span class="mk mk-vis" style="margin: 0 4px 2px 0;"></span>Visitor submitted</span><span><span class="mk mk-ai" style="margin: 0 4px 2px 0;"></span>AI guess</span></span></div>
<sc-for list="{{q.lines}}" as="l" hint-placeholder-count="3"><p>{{l.t}}<span class="mk mk-{{l.m}}"></span><span class="cite">{{l.c}}</span></p></sc-for>
<span class="sub">Tap a business below for its full record and references. Nobody pays to appear in answers.</span></div>
<div class="res">
<div style="display: flex; flex-direction: column; gap: 12px;"><div style="display: flex; align-items: baseline; justify-content: space-between;"><h2 style="margin: 0; font-size: 22px; font-weight: 600;">{{q.count}} med spas match</h2><label style="font-size: 13px; color: #6a6a6a;">Sort by <select style="height: 32px; border: 1px solid #dddddd; border-radius: 16px; padding: 0 10px; font-family: inherit; font-weight: 600;"><option>Best fit</option><option>AI Score</option><option>Rating</option><option>Distance</option></select></label></div>
<sc-for list="{{q.biz}}" as="b" hint-placeholder-count="6"><a href="{{b.href}}" class="bc"><span class="bph" style="background: {{b.bg}};">[{{b.ph}}]</span><span style="display: flex; flex-direction: column; gap: 5px; min-width: 0;"><span style="display: flex; justify-content: space-between; gap: 8px; align-items: center;"><strong style="font-size: 16px;">{{b.i}}. {{b.n}}</strong><span class="sc" style="background: {{b.sbg}}; color: {{b.sc}};">AI {{b.s}}</span></span><span class="mu" style="font-size: 13px;">{{b.cat}} · {{b.city}} · {{b.dist}}</span><span style="font-size: 13px;">★ {{b.r}} · {{b.rv}} reviews · {{b.price}}</span><span style="font-size: 13px; color: #484848;">{{b.why}}</span><span style="display: flex; gap: 6px; flex-wrap: wrap; margin-top: 2px;"><span class="tag {{b.tc}}" style="height: 22px; font-size: 11px;">{{b.tag}}</span><span class="tag grn" style="height: 22px; font-size: 11px; display: {{b.cb}};">20% cashback</span><span class="tag gry" style="height: 22px; font-size: 11px;">{{b.now}}</span></span></span></a></sc-for>
<div class="card" style="padding: 20px 22px; display: flex; align-items: center; justify-content: space-between; gap: 20px; background: #fafafa; border-style: dashed;"><div style="display: flex; flex-direction: column; gap: 4px;"><strong style="font-size: 16px;">Not finding the right fit?</strong><span class="mu" style="font-size: 14px; line-height: 20px;">Tell us what you want, when and your budget. Matching businesses reply with real openings. Your name stays hidden until you pick one.</span></div><a href="Request.dc.html" class="btn b-dark" style="flex-shrink: 0;">Post a request</a></div>
</div>
<div class="map"><span class="road" style="left: 0; right: 0; top: 38%; height: 10px; transform: rotate(-8deg);"></span><span class="road" style="top: 0; bottom: 0; left: 44%; width: 12px; transform: rotate(12deg);"></span><span class="road" style="left: 0; right: 0; top: 72%; height: 7px;"></span><span class="road" style="top: 0; bottom: 0; left: 78%; width: 7px;"></span><span style="position: absolute; left: 48%; top: 46%; width: 90px; height: 60px; border-radius: 12px; background: #d9e6d3;"></span><span style="position: absolute; left: 50%; top: 58%; font-size: 11px; font-weight: 600; color: #5a6b55;">Irvine Spectrum</span>
<sc-for list="{{q.biz}}" as="b" hint-placeholder-count="6"><span class="pin {{b.pin}}" style="left: {{b.x}}%; top: {{b.y}}%;">{{b.i}} · AI {{b.s}}</span></sc-for>
<span style="position: absolute; right: 12px; bottom: 12px; font-size: 11px; color: #6a6a6a; background: #ffffff; padding: 4px 8px; border-radius: 6px;">Map data placeholder</span></div>
</div>
<div style="display: flex; flex-direction: column; gap: 12px;"><h2 style="margin: 0; font-size: 22px; font-weight: 600;">Browse by category</h2><div class="rail"><sc-for list="{{cats}}" as="c" hint-placeholder-count="8"><a href="#" class="rc"><strong style="font-size: 15px;">{{c.n}}</strong><span class="mu" style="font-size: 12px;">{{c.c}} near Irvine</span></a></sc-for></div></div>
<div style="display: flex; flex-direction: column; gap: 12px;"><h2 style="margin: 0; font-size: 22px; font-weight: 600;">Cities in Orange County</h2><div class="rail"><sc-for list="{{cities}}" as="c" hint-placeholder-count="6"><a href="#" class="rc"><strong style="font-size: 15px;">{{c.n}}</strong><span class="mu" style="font-size: 12px;">{{c.c}} businesses</span></a></sc-for></div></div>
<div style="display: flex; flex-direction: column; gap: 12px;"><h2 style="margin: 0; font-size: 22px; font-weight: 600;">New nearby</h2><div class="news"><sc-for list="{{news}}" as="n" hint-placeholder-count="4"><div class="nw"><span class="mu" style="font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em;">{{n.k}}</span><strong style="font-size: 14px;">{{n.t}}</strong><span style="color: #484848;">{{n.d}}</span></div></sc-for></div></div>
<div class="card" style="padding: 26px 28px; display: grid; grid-template-columns: 1fr auto; gap: 24px; align-items: center; background: #222222; border-color: #222222; color: #ffffff;"><div style="display: flex; flex-direction: column; gap: 6px;"><strong style="font-size: 20px;">Own a business? See what AI says about it.</strong><span style="font-size: 14px; line-height: 21px; color: #d0d0d0;">Your page is probably already here. Claim it free, fix what AI gets wrong, and answer your customers.</span></div><a href="Main.dc.html" class="btn b-coral">Find my business</a></div>
</div>
<footer style="margin-top: auto; padding: 24px 120px; border-top: 1px solid #ebebeb; display: flex; justify-content: space-between; font-size: 13px; color: #6a6a6a;"><span>Local AI Registry · Irvine, CA</span><span style="display: flex; gap: 16px;"><a href="#" style="font-weight: 500;">How records are built</a><a href="#" style="font-weight: 500;">For developers</a><a href="Claim.dc.html" style="font-weight: 500;">For businesses</a></span></footer>'''
JS=r'''    const qi = (this.state && this.state.qi) || 0;
    const B = {
      lumen: ['Lumen Aesthetics', 'Medical spa', 'Irvine', '0.4 mi', '4.9', '612', '$$$', 58, 'Unclaimed', 'red', 'none', 'Quiet now', 'Main.dc.html', '#e8d9cf', 'Treatment room', 52, 52],
      coast: ['Coastline MedSpa', 'Medical spa', 'Newport Beach', '6.1 mi', '4.8', '890', '$$$', 84, 'Claimed', 'grn', 'inline-flex', 'Busy now', 'Main.dc.html', '#d9dfe8', 'Front desk', 22, 78],
      derm: ['Derm + Co', 'Dermatologist', 'Tustin', '5.3 mi', '4.7', '340', '$$', 77, 'Claimed', 'grn', 'none', 'Quiet now', 'Main.dc.html', '#dfe8d9', 'Exam room', 30, 18],
      spec: ['Spectrum Aesthetics MD', 'Medical spa', 'Irvine', '0.9 mi', '4.8', '402', '$$$', 81, 'Claimed', 'grn', 'inline-flex', 'Usually busy at 1 PM', 'Main.dc.html', '#f0dfd0', 'Lobby', 60, 40],
      pac: ['Pacific Skin Studio', 'Skin care clinic', 'Irvine', '1.8 mi', '4.6', '210', '$$', 69, 'Unclaimed', 'red', 'none', 'Quiet now', 'Main.dc.html', '#e4e0ef', 'Studio', 70, 64],
      glow: ['Glow Bar Irvine', 'Facial spa', 'Irvine', '2.4 mi', '4.5', '150', '$$', 52, 'Unclaimed', 'red', 'none', 'Open until 8 PM', 'Main.dc.html', '#efe7d6', 'Facial room', 84, 30]
    };
    const Q = [
      { t: 'Natural lip filler that takes HSA', q: 'Who does natural-looking lip filler in Irvine and takes HSA cards?', src: '41', count: '6', order: [['lumen', 'Half syringes offered, Dr. Nair or a nurse injects, takes HSA'], ['spec', 'Doctor-led, takes HSA, books about 2 weeks out'], ['coast', 'Most lip filler reviews in Orange County, takes HSA'], ['derm', 'Dermatologist, fewer filler reviews'], ['pac', 'Nurse injectors, HSA not confirmed'], ['glow', 'Facials only, no filler']], lines: [['Lumen Aesthetics and Spectrum Aesthetics MD are the two Irvine med spas where a doctor or licensed nurse does every lip filler and HSA cards are accepted.', 'site', '1'], ['Lumen is the one most often described as natural-looking: 31 reviews mention being talked out of more filler, and half syringes are $450.', 'vis', '2'], ['Coastline MedSpa in Newport Beach has the most lip filler reviews in the county, but it is 6 miles away and books about 3 weeks out.', 'ai', '3']] },
      { t: 'Botox open Saturday near Irvine Spectrum', q: 'Where can I get Botox on a Saturday near Irvine Spectrum?', src: '28', count: '4', order: [['lumen', 'Open Saturday 9 AM to 7 PM, $12 a unit, inside Irvine Spectrum'], ['spec', 'Open Saturday until 3 PM, $13 a unit'], ['glow', 'Open Saturday, but no Botox'], ['coast', 'Saturday appointments, $14 a unit']], lines: [['Lumen Aesthetics is inside Irvine Spectrum Center and open Saturdays 9 AM to 7 PM, at $12 a unit.', 'site', '1'], ['Saturday afternoons at Lumen run about 25 minutes behind, so book before noon.', 'vis', '2'], ['Spectrum Aesthetics MD, 0.9 miles away, is also open Saturday until 3 PM.', 'ai', '3']] },
      { t: 'Dermatologist-led med spa in Orange County', q: 'What is the best dermatologist-led med spa in Orange County?', src: '57', count: '5', order: [['derm', 'Two board-certified dermatologists'], ['lumen', 'Owned and led by a board-certified dermatologist'], ['spec', 'Physician-led, not a dermatologist'], ['coast', 'Medical director is a family physician'], ['pac', 'No physician on staff listed']], lines: [['Derm + Co in Tustin and Lumen Aesthetics in Irvine are the two med spas where a board-certified dermatologist treats patients.', 'site', '1'], ['Lumen scores higher on reviews, 4.9 across 612, and is known for saying no when a treatment is not needed.', 'site', '2'], ['Coastline MedSpa is often named by AI engines, but its medical director is a family physician, not a dermatologist.', 'ai', '3']] }
    ];
    const cur = Q[qi];
    const chips = Q.map((x, i) => ({ t: x.t, on: i === qi ? 'on' : '', pick: () => this.setState({ qi: i }) }));
    const q = { q: cur.q, src: cur.src, count: cur.count, lines: cur.lines.map(l => ({ t: l[0], m: l[1], c: l[2] })), biz: cur.order.map((o, i) => { const b = B[o[0]]; return { i: String(i + 1), n: b[0], cat: b[1], city: b[2], dist: b[3], r: b[4], rv: b[5], price: b[6], s: String(b[7]), sbg: b[7] >= 75 ? '#ddf1e1' : b[7] >= 60 ? '#fdeeda' : '#fbe9e7', sc: b[7] >= 75 ? '#237233' : b[7] >= 60 ? '#b86a00' : '#c13515', tag: b[8], tc: b[9], cb: b[10], now: b[11], href: b[12], bg: b[13], ph: b[14], x: String(b[15]), y: String(b[16]), why: o[1], pin: i === 0 ? 'on' : '' }; }) };
    const cats = [['Med spas', '48'], ['Dermatologists', '31'], ['Dentists', '112'], ['Plastic surgeons', '24'], ['Eye doctors', '37'], ['Dispensaries', '9'], ['Hair salons', '140'], ['Chiropractors', '52']].map(c => ({ n: c[0], c: c[1] }));
    const cities = [['Irvine', '4,120'], ['Newport Beach', '2,310'], ['Tustin', '1,480'], ['Costa Mesa', '2,050'], ['Lake Forest', '980'], ['Mission Viejo', '1,260']].map(c => ({ n: c[0], c: c[1] }));
    const news = [['Just claimed', 'Spectrum Aesthetics MD', 'Confirmed 38 facts and answered 12 questions this week.'], ['AI got it wrong', 'Lumen Aesthetics hours', 'ChatGPT says open Mondays. Their record says closed.'], ['New service', 'Morpheus8 Body at Lumen', 'Consults open October 1, per their own post.'], ['New on the registry', 'Glow Bar Irvine', 'Facial spa, opened August 2026.']].map(n => ({ k: n[0], t: n[1], d: n[2] }));
    return { q, chips, cats, cities, news };'''
open(P+'Home.dc.html','w').write(page('Local AI Registry: ask about local businesses',CSS,BODY,JS))
print('home ok')
