import sys; sys.path.insert(0,'/tmp/gen'); from common import *
CSS=r'''.mw{max-width:880px;margin:0 auto;padding:36px 40px 64px;display:flex;flex-direction:column;gap:22px}
.ph{display:flex;gap:18px;align-items:center}
.av{width:72px;height:72px;border-radius:50%;background:#dfe8f5;color:#13203a;display:flex;align-items:center;justify-content:center;font-size:24px;font-weight:700;flex-shrink:0}
.bdgx{display:inline-flex;align-items:center;gap:5px;height:24px;padding:0 10px;border-radius:12px;background:#e8eefc;color:#2b59d9;font-size:12px;font-weight:700}
.tabs{display:flex;gap:4px;border-bottom:1px solid #e4ded2}
.tabs > span{padding:12px 14px;font-size:14px;font-weight:600;color:#667085;cursor:pointer;border-bottom:2px solid transparent;margin-bottom:-1px}
.tabs > span.on{color:#13203a;border-bottom-color:#13203a}
.it{display:flex;flex-direction:column;gap:6px;padding:16px 0;border-bottom:1px solid #ece6da}
.it .m{font-size:12px;color:#667085}.it .m a{font-weight:600}
.it strong{font-size:16px}.it p{margin:0;font-size:14px;line-height:21px;color:#3d4658}
.st{display:inline-flex;height:22px;padding:0 9px;border-radius:11px;font-size:11px;font-weight:700;align-items:center}
.ok{background:#e3f4e6;color:#1c5f2a}.pd{background:#fff1e0;color:#9a5a00}.no{background:#efeae0;color:#667085}
.pl{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:14px 0;border-bottom:1px solid #ece6da}
.srow{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:14px 0;border-bottom:1px solid #ece6da;font-size:14px}
.srow .k{display:flex;flex-direction:column;gap:2px}.srow .k span{font-size:13px;color:#667085}
.sh3{font-size:12px;font-weight:700;letter-spacing:0.08em;text-transform:uppercase;color:#667085;margin-top:18px}
'''
B=header('<a href="ExploreMe.dc.html" class="btn b-sm">Back to Explore</a><a href="Post.dc.html" class="btn b-sm b-coral">Post</a>')+'''<div class="mw"><div class="ph"><span class="av">W</span><div style="display: flex; flex-direction: column; gap: 4px;"><span style="display: flex; align-items: center; gap: 10px;"><strong style="font-size: 24px;">woodbridge_mom_of_2</strong><span class="bdgx">★ Local expert</span></span><span style="font-size: 14px; line-height: 21px; color: #3d4658;">Mom of two, eats out way too much, will tell you where the kids can run around.</span><span class="mu" style="font-size: 13px;">Active in Irvine · Joined March 2026 · 38 fixes accepted by owners</span></div></div>
<div class="tabs"><sc-for list="{{tabs}}" as="t" hint-placeholder-count="5"><span class="{{t.cls}}" onClick="{{t.pick}}">{{t.n}}</span></sc-for></div>
<sc-if value="{{isList}}" hint-placeholder-val="{{ true }}"><div><sc-for list="{{items}}" as="i" hint-placeholder-count="4"><a href="Thread.dc.html" class="it" style="text-decoration: none; color: inherit;"><span class="m">{{i.m}}</span><strong>{{i.t}}</strong><p>{{i.p}}</p></a></sc-for></div></sc-if>
<sc-if value="{{isPlaces}}" hint-placeholder-val="{{ false }}"><div><span class="sh3">Places you've posted about, replied to or edited</span><sc-for list="{{places}}" as="p" hint-placeholder-count="4"><a href="Main.dc.html" class="pl" style="text-decoration: none; color: inherit;"><span style="display: flex; flex-direction: column; gap: 2px;"><strong>{{p.n}}</strong><span class="mu" style="font-size: 13px;">{{p.s}}</span></span><span class="mu" style="font-size: 13px;">{{p.w}}</span></a></sc-for><span class="sh3">Suggested for you</span><span class="mu" style="font-size: 13px;">Based on the places you've engaged with.</span><sc-for list="{{sugg}}" as="p" hint-placeholder-count="3"><a href="Main.dc.html" class="pl" style="text-decoration: none; color: inherit;"><span style="display: flex; flex-direction: column; gap: 2px;"><strong>{{p.n}}</strong><span class="mu" style="font-size: 13px;">{{p.s}}</span></span><span style="font-size: 13px; color: #2b59d9; font-weight: 600;">{{p.w}}</span></a></sc-for></div></sc-if>
<sc-if value="{{isEdits}}" hint-placeholder-val="{{ false }}"><div><span class="sh3">Changes you suggested and places you added</span><sc-for list="{{edits}}" as="e" hint-placeholder-count="5"><div class="pl"><span style="display: flex; flex-direction: column; gap: 2px;"><strong>{{e.t}}</strong><span class="mu" style="font-size: 13px;">{{e.s}}</span></span><span class="st {{e.c}}">{{e.st}}</span></div></sc-for></div></sc-if>
<sc-if value="{{isSet}}" hint-placeholder-val="{{ false }}"><div><span class="sh3">Profile</span><div class="srow"><span class="k"><strong>Username</strong><span>woodbridge_mom_of_2</span></span><a href="#">Change</a></div><div class="srow"><span class="k"><strong>Bio</strong><span>Mom of two, eats out way too much...</span></span><a href="#">Edit</a></div><div class="srow"><span class="k"><strong>City you're active in</strong><span>Irvine</span></span><a href="#">Change</a></div>
<span class="sh3">Sign-in</span><div class="srow"><span class="k"><strong>Email</strong><span>maya.t@gmail.com</span></span><a href="#">Change</a></div><div class="srow"><span class="k"><strong>Mobile</strong><span>(949) 555-0164</span></span><a href="#">Change</a></div><div class="srow"><span class="k"><strong>Password</strong><span>Last changed Aug 2026</span></span><a href="#">Change</a></div><div class="srow"><span class="k"><strong>Sign in with Google</strong><span>Connected</span></span><a href="#">Disconnect</a></div>
<span class="sh3">Notifications</span><div class="srow"><span>Someone replies to me</span><span>Email</span></div><div class="srow"><span>An owner accepts or declines my suggestion</span><span>Email</span></div><div class="srow"><span>Booking replies</span><span>Email and text</span></div>
<span class="sh3">Your data</span><div class="srow"><span class="k"><strong>Download your data</strong><span>Posts, replies and suggestions, as a ZIP file</span></span><span class="btn b-sm">Download</span></div><div class="srow"><span class="k"><strong style="color: #c13515;">Delete account</strong><span>Your posts stay up, credited to "deleted user"</span></span><span class="btn b-sm" style="color: #c13515;">Delete</span></div></div></sc-if></div>'''
JS=r'''    const S = this.state || {}; const tab = S.tab || 0;
    const TB = ['Posts', 'Replies', 'Places', 'Edits', 'Settings'];
    const tabs = TB.map((n, i) => ({ n, cls: i === tab ? 'on' : '', pick: () => this.setState({ tab: i }) }));
    const POSTS = [['Tip · Lumen Aesthetics · Sep 22', 'Ask for level 3 in Structure B', 'Shade all day and you walk right into the Spectrum. Validate at the front desk.'], ['Question · Paperbird Cafe · Sep 10', 'Is the patio kid-friendly on weekends?', 'Two kids under 6, want somewhere they can move around.'], ['Heads-up · Glow Bar Irvine · Aug 28', 'Closed for remodel until Sep 5', 'Sign on the door says reopening the 5th.']];
    const REPL = [['Replied to "Best tacos near Woodbridge?" · Taqueria Chuy · Sep 24', 'Go at 11:30 before the line', 'Al pastor is the move. Cash only on the truck.'], ['Replied to "Does Dr. Nair do lip filler herself?" · Lumen Aesthetics · Sep 25', 'She did mine in March', 'Talked me down to half a syringe, which was the right call.'], ['Replied to "Weekend brunch with a stroller?" · Paperbird Cafe · Sep 12', 'Yes, ask for the back room', 'Wide aisles and a changing table.']];
    const list = tab === 0 ? POSTS : REPL;
    const items = list.map(x => ({ m: x[0], t: x[1], p: x[2] }));
    const places = [['Lumen Aesthetics', 'Med spa · Irvine Spectrum', '1 tip, 1 reply, 2 edits'], ['Paperbird Cafe', 'Cafe · Woodbridge', '1 question, 1 reply'], ['Taqueria Chuy', 'Tacos · Irvine', '1 reply, 1 edit'], ['Glow Bar Irvine', 'Med spa · Woodbridge', '1 heads-up']].map(p => ({ n: p[0], s: p[1], w: p[2] }));
    const sugg = [['Mama Tried Kitchen', 'Family restaurant · Woodbridge · locals mention the play area', 'See what locals say'], ['Coastline Med Spa', 'Med spa · Irvine · similar to Lumen', 'See what locals say'], ['Sol Tacos', 'Tacos · Northwood · 41 posts this month', 'See what locals say']].map(p => ({ n: p[0], s: p[1], w: p[2] }));
    const edits = [['Lumen Aesthetics: parking is Structure B, level 3', 'You went there · Sep 21', 'Accepted by owner', 'ok'], ['Taqueria Chuy: cash only on the truck', 'You went there · Sep 18', 'Accepted by owner', 'ok'], ['Paperbird Cafe: opens 7 AM on weekends', 'You called · Sep 26', 'Waiting on owner', 'pd'], ['Glow Bar Irvine: closed Mondays', 'You called · Aug 30', 'Not accepted', 'no'], ['Added a place: Little Sprouts Play Cafe', 'Woodbridge · Aug 14', 'Added', 'ok']].map(e => ({ t: e[0], s: e[1], st: e[2], c: e[3] }));
    return { tabs, items, places, sugg, edits, isList: tab < 2, isPlaces: tab === 2, isEdits: tab === 3, isSet: tab === 4 };'''
open(P+'Me.dc.html','w').write(page('Consumer profile',CSS,B,JS)); print('ok')
