DATA=open('/tmp/gen/premdata.js').read()
CSS += r""".ptabs{display:inline-flex;padding:4px;border-radius:14px;background:#efefef;gap:2px}
.ptabs .ptb{display:inline-flex;align-items:center;gap:8px;height:40px;padding:0 18px;border-radius:11px;cursor:pointer;font-size:14px;font-weight:700;color:#484848}
.ptabs .ptb.on{background:#ffffff;color:#222222;box-shadow:0 1px 4px rgba(0,0,0,0.12)}
.ptabs .ptb i{font-style:normal;font-size:10px;font-weight:700;padding:2px 7px;border-radius:8px;background:#222222;color:#ffffff}
.pg{display:grid;grid-template-columns:330px 1fr;gap:20px;align-items:start}
.minis{display:grid;grid-template-columns:230px 220px 1fr;gap:12px}
.mini{background:#ffffff;border:1px solid #e6e6e6;border-radius:14px;padding:12px 14px;display:flex;flex-direction:column;gap:6px;min-width:0}
.mini .mh{display:flex;justify-content:space-between;align-items:baseline;font-size:12px;font-weight:700;color:#484848}
.mini .mh a{font-size:11px;font-weight:600}
.mrow{display:flex;justify-content:space-between;align-items:center;font-size:12px;padding:3px 0;border-top:1px solid #f3f3f3}
.mrow:first-of-type{border-top:none}
.mrow.miss{color:#c13515}
.mrow span:first-child{white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:200px}
.mcal4{display:grid;grid-template-columns:repeat(7,1fr);gap:2px}
.mcal4 .h{font-size:10px;font-weight:700;color:#8a8a8a;text-align:center;padding:2px 0}
.mcal4 .d{display:flex;flex-direction:column;align-items:center;gap:3px;padding:4px 1px 5px;border-radius:9px;cursor:pointer;font-size:12px;font-weight:600;min-height:46px;box-sizing:border-box}
.mcal4 .d:hover{background:#f3f3f3}
.mcal4 .d.on{background:#222222;color:#ffffff}
.mcal4 .d.off{color:#d0d0d0;cursor:default}
.mcal4 .dots{display:grid;grid-template-columns:repeat(4,5px);gap:2px;justify-content:center}
.mcal4 .dots i{width:5px;height:5px;border-radius:50%;display:block}
.mcal4 .dots i.lk{opacity:0.3}
.types2{display:grid;grid-template-columns:1fr;gap:0}
.ty3{display:flex;align-items:center;gap:8px;padding:5px 6px;border-radius:7px;cursor:pointer;font-size:12px}
.ty3:hover{background:#f5f5f5}
.ty3 .sw{width:10px;height:10px;border-radius:3px;flex-shrink:0}
.ty3.offt{opacity:0.35}
.ty3 .lk{margin-left:auto;font-size:10px;color:#8a8a8a}
.pbig{background:#ffffff;line-height:normal;border:1px solid #e4ded2;border-radius:16px;padding:16px 18px;display:flex;flex-direction:column;gap:14px}
.ctop{display:grid;grid-template-columns:1fr 210px;gap:18px}
.tfs{display:inline-flex;gap:2px}.tfs span{height:28px;padding:0 10px;border-radius:14px;display:inline-flex;align-items:center;font-size:12px;font-weight:700;color:#667085;cursor:pointer}.tfs span.on{background:#e8eefc;color:#2b59d9}
.rl{display:flex;flex-direction:column;border-left:1px solid #ece6da;padding-left:14px}
.rpa{width:24px;height:24px;border-radius:50%;border:1px solid #dcd5c7;display:inline-flex;align-items:center;justify-content:center;font-size:14px;cursor:pointer;color:#13203a}
.rr{color:#13203a;display:flex;justify-content:space-between;align-items:center;padding:6px 8px;border-radius:8px;font-size:13px;cursor:pointer}.rr:hover{background:#f3efe7}.rr.on{background:#13203a;color:#ffffff}.rr.on .up{color:#9fe0ad}.rr .up{color:#237233;font-weight:700;font-size:12px}
.aiq{line-height:18px;display:grid;grid-template-columns:1.6fr 70px 70px 70px 70px 1.1fr;gap:8px;align-items:center;font-size:12px;padding:6px 0;border-top:1px solid #f0ebe1}
.aiq.h{font-size:10px;font-weight:700;letter-spacing:0.06em;text-transform:uppercase;color:#8a8a8a;border-top:none}
.aiq .y{color:#237233;font-weight:700}.aiq .n{color:#c13515}
.dch{display:flex;flex-wrap:wrap;gap:6px}.dch .chip{height:32px;padding:0 12px;border-radius:16px;border:1px solid #e4ded2;background:#ffffff;display:inline-flex;align-items:center;gap:6px;font-size:13px;font-weight:700;color:#484848;cursor:pointer}.dch .chip b{font-size:11px;color:#8a8a8a}.dch .chip.on{background:#13203a;border-color:#13203a;color:#ffffff}.dch .chip.on b{color:#c9d0dc}
.dch-ch{font-size:11px;font-weight:700;color:#5b6474;background:#f3efe7;border-radius:10px;padding:3px 8px;white-space:nowrap}
.dlink{display:inline-flex;align-items:center;gap:5px;font-size:12px;font-weight:700;color:#2b59d9;white-space:nowrap}.dicon{align-items:center}
.dprev{padding:10px 14px;border-radius:12px;background:#fbf4ea;border:1px solid #f0dcc4;font-size:13px;color:#3d4658;display:flex;justify-content:space-between;align-items:center;gap:12px}
.p-dl{background:#e6f2e8;color:#1c5f2a}
.emp{padding:28px;border-radius:14px;border:1px dashed #dcd5c7;text-align:center;font-size:14px;color:#3d4658}
.tgrp{font-size:10px;font-weight:700;letter-spacing:0.08em;text-transform:uppercase;color:#8a8a8a;padding:8px 6px 2px}
"""
prem = """<div style="display: flex; justify-content: space-between; align-items: center; gap: 16px;"><span style="display: flex; align-items: center; gap: 18px;"><h1 class="ttl1">Premium</h1><span class="ptabs"><sc-for list="{{tabs}}" as="t" hint-placeholder-count="4"><span class="ptb {{t.cls}}" onClick="{{t.pick}}">{{t.n}}<i style="display: {{t.cd}};">Your plan</i></span></sc-for></span></span><span style="display: flex; align-items: center; gap: 10px;"><a href="Next.dc.html" class="btn b-sm">Run a free AI audit</a><span class="mu" style="font-size: 13px;">{{ctaT}}</span><sc-if value="{{ctaOn}}" hint-placeholder-val="{{ true }}"><a href="Upgrade.dc.html" class="btn b-sm b-coral">{{ctaB}}</a></sc-if></span></div>
<div class="pg"><div style="display: flex; flex-direction: column; gap: 12px; position: sticky; top: 16px;">
<div class="card" style="padding: 12px 12px 10px; gap: 6px;"><div style="display: flex; justify-content: space-between; align-items: center; padding: 0 4px;"><strong style="font-size: 14px;">October 2026</strong><span class="mu" style="font-size: 11px;">{{nAll}} pieces in {{vName}}</span></div><div class="mcal4"><sc-for list="{{dowS}}" as="d" hint-placeholder-count="7"><span class="h">{{d}}</span></sc-for><sc-for list="{{mcal}}" as="c" hint-placeholder-count="35"><span class="d {{c.cls}}" onClick="{{c.pick}}">{{c.n}}<span class="dots"><sc-for list="{{c.dots}}" as="o" hint-placeholder-count="4"><i class="{{o.k}}" style="background: {{o.c}};"></i></sc-for></span></span></sc-for></div></div>
<div class="card" style="padding: 8px 10px; gap: 0;"><sc-for list="{{groups}}" as="g" hint-placeholder-count="3"><span class="tgrp">{{g.n}}</span><sc-for list="{{g.types}}" as="y" hint-placeholder-count="6"><span class="ty3 {{y.cls}}" onClick="{{y.pick}}"><span class="sw" style="background: {{y.c}};"></span>{{y.n}}<span class="lk">{{y.k}}</span></span></sc-for></sc-for></div>
<a href="OwnerNotes.dc.html" style="display: flex; align-items: center; gap: 10px; padding: 10px 12px; border-radius: 12px; border: 1px solid #e6e6e6; background: #ffffff; text-decoration: none; color: #222222; font-size: 13px;"><span style="width: 26px; height: 26px; border-radius: 50%; background: #13203a; color: #ffffff; display: flex; align-items: center; justify-content: center; font-size: 12px;">✎</span><strong>AI notes</strong><span class="mu" style="font-size: 12px;">5 notes</span><span style="margin-left: auto;">›</span></a></div>
<div style="display: flex; flex-direction: column; gap: 14px;"><div class="pbig"><div class="ctop"><div style="display: flex; flex-direction: column; gap: 8px; min-width: 0;"><div style="display: flex; justify-content: space-between; align-items: flex-start; gap: 10px;"><span style="display: flex; flex-direction: column;"><span class="mu" style="font-size: 12px; font-weight: 700;">AI Visibility Score</span><span style="display: flex; align-items: baseline; gap: 8px;"><b style="font-size: 32px; line-height: 38px;">{{hv}}</b><span style="font-size: 13px; font-weight: 700; color: #237233;">{{hch}}</span><span class="mu" style="font-size: 12px;">{{hl}}</span></span></span><span class="tfs"><sc-for list="{{tfs}}" as="f" hint-placeholder-count="5"><span class="{{f.cls}}" onClick="{{f.pick}}">{{f.n}}</span></sc-for></span></div>
<svg viewBox="0 0 600 190" width="100%" height="190" aria-label="AI Visibility Score over time"><text x="10" y="80" font-size="10" fill="#667085" transform="rotate(-90 10 80)" text-anchor="middle">AI Score (0 to 100)</text><text x="315" y="186" font-size="10" fill="#667085" text-anchor="middle">{{xl}}</text><sc-for list="{{grid}}" as="g" hint-placeholder-count="4"><line x1="40" x2="600" y1="{{g.y}}" y2="{{g.y}}" stroke="#efeae0"></line><text x="20" y="{{g.ty}}" font-size="10" fill="#8a8a8a">{{g.v}}</text></sc-for><polygon points="{{area}}" fill="#2b59d9" opacity="0.08"></polygon><polyline points="{{line}}" fill="none" stroke="#2b59d9" stroke-width="2.5"></polyline><polyline points="{{fline}}" fill="none" stroke="#237233" stroke-width="2.5" stroke-dasharray="5 4"></polyline><sc-for list="{{pts}}" as="p" hint-placeholder-count="8"><g onClick="{{p.pick}}" style="cursor: pointer;"><circle cx="{{p.x}}" cy="{{p.y}}" r="12" fill="transparent"></circle><circle cx="{{p.x}}" cy="{{p.y}}" r="{{p.r}}" fill="{{p.c}}" stroke="#ffffff" stroke-width="2"></circle><text x="{{p.x}}" y="166" font-size="10" fill="#8a8a8a" text-anchor="middle">{{p.l}}</text></g></sc-for><sc-for list="{{flabs}}" as="p" hint-placeholder-count="3"><text x="{{p.x}}" y="166" font-size="10" fill="#237233" text-anchor="middle">{{p.l}}</text></sc-for></svg>
<span class="mu" style="font-size: 11px;"><span style="color: #2b59d9; font-weight: 700;">━</span> Measured monthly by Local AI Registry · <span style="color: #237233; font-weight: 700;">┅</span> Forecast on {{vName}}, {{proj}} by March</span></div>
<div class="rl"><span style="display: flex; justify-content: space-between; align-items: center; padding: 0 8px 6px;"><span class="mu" style="font-size: 12px; font-weight: 700;">Monthly reports</span><span style="display: flex; gap: 4px;"><span class="rpa" onClick="{{repPrev}}" style="opacity: {{rpo}};">‹</span><span class="rpa" onClick="{{repNext}}" style="opacity: {{rno}};">›</span></span></span><sc-for list="{{reps}}" as="r" hint-placeholder-count="3"><a href="MonthReport.dc.html" class="rr {{r.cls}}" style="text-decoration: none;"><span>{{r.m}} report</span><span style="color: #8a93a3;">›</span></a></sc-for><a href="MonthReport.dc.html" style="font-size: 12px; font-weight: 600; padding: 8px 8px 0; color: #2b59d9;">All reports</a></div></div>
<div><div style="display: flex; justify-content: space-between; align-items: baseline;"><strong style="font-size: 14px;">What people ask AI</strong><span class="mu" style="font-size: 11px;">Checked Oct 1 on ChatGPT, Gemini and Claude</span></div><div class="aiq h" style="grid-template-columns: 1.6fr 90px 1.4fr;"><span>Prompt</span><span>Searches / mo</span><span>Does AI name Lumen?</span></div><sc-for list="{{prompts}}" as="p" hint-placeholder-count="5"><div class="aiq" style="grid-template-columns: 1.6fr 90px 1.4fr;"><span>{{p.q}}</span><span>{{p.v}}</span><span class="{{p.c}}">{{p.who}}</span></div></sc-for></div></div>
<sc-if value="{{emptyM}}" hint-placeholder-val="{{ false }}"><div class="emp">Free has no work on it. Pick <strong>Fix</strong> to see a directory submission land every day.</div></sc-if>
<div style="display: flex; justify-content: space-between; align-items: center; gap: 12px;"><span class="ptabs"><span class="ptb {{m1c}}" onClick="{{setM1}}">To approve<i style="display: inline;">{{nAp}}</i></span><span class="ptb {{m2c}}" onClick="{{setM2}}">Approved and delivered<i style="display: inline; background: #237233;">{{nDel}}</i></span></span></div><sc-if value="{{modeCal}}" hint-placeholder-val="{{ true }}"><div class="agenda"><div style="display: flex; justify-content: space-between; align-items: baseline;"><strong style="font-size: 17px;">{{rangeLbl}}</strong><span style="display: flex; gap: 8px;"><sc-if value="{{canAct}}" hint-placeholder-val="{{ true }}"><span class="btn b-sm b-dark" onClick="{{approveAll}}">Approve all {{nAp}}</span></sc-if><span class="btn b-sm" onClick="{{showAll}}">Whole month</span></span></div>
<sc-for list="{{days}}" as="g" hint-placeholder-count="3"><div style="display: flex; flex-direction: column; gap: 8px;"><span class="dayh">{{g.d}}<span class="mu" style="font-weight: 500;">{{g.n}} · {{g.c}} pieces</span></span><sc-for list="{{g.items}}" as="i" hint-placeholder-count="2"><div class="itm2 {{i.lk}}"><div class="row" onClick="{{i.pick}}" style="padding: 11px 14px;"><span class="bar2" style="background: {{i.c}};"></span><span class="tt"><strong style="font-size: 14px;">{{i.t}}</strong><span>{{i.ty}} · {{i.dest}}</span></span><span class="pill {{i.pc}}">{{i.st}}</span><span style="font-size: 12px; color: #6a6a6a;">{{i.car}}</span></div>
<sc-if value="{{i.open}}" hint-placeholder-val="{{ false }}"><sc-if value="{{i.act}}" hint-placeholder-val="{{ true }}"><div class="exp"><div style="display: flex; flex-direction: column; gap: 8px;"><div class="img" style="display: {{i.imd}};">[Image: {{i.img}}]</div><span class="mu" style="font-size: 12px;">Follows your AI notes</span></div><div style="display: flex; flex-direction: column; gap: 12px;"><div class="body2">{{i.body}}</div><span style="display: flex; gap: 8px;"><span class="btn b-sm b-dark" onClick="{{i.approve}}">Approve</span><span class="btn b-sm">Edit</span><span class="btn b-sm">Skip</span></span><div class="note2"><strong style="font-size: 13px;">Add an AI note and rewrite</strong><textarea placeholder="e.g. Mention the free parking in Structure B" onChange="{{onNote}}">{{noteTxt}}</textarea><span style="display: flex; gap: 10px; align-items: center;"><span class="btn b-sm b-dark" onClick="{{i.rewrite}}">Rewrite with this note</span><span class="mu" style="font-size: 12px;">Saved to AI notes.</span></span></div></div></div></sc-if>
<sc-if value="{{i.locked}}" hint-placeholder-val="{{ false }}"><div style="display: flex; align-items: center; justify-content: space-between; gap: 12px; margin: 0 16px 14px 30px; padding: 12px 14px; border-radius: 12px; background: #f3f3f3;"><span style="font-size: 13px; color: #484848;">🔒 Part of {{i.tn}}. Upgrade to see and approve it.</span><a href="Upgrade.dc.html" class="btn b-sm b-coral">Upgrade to {{i.tn}}</a></div></sc-if></sc-if></div></sc-for></div></sc-for><sc-if value="{{showPg}}" hint-placeholder-val="{{ true }}"><div style="display: flex; justify-content: space-between; align-items: center; padding-top: 6px;"><span class="btn b-sm" onClick="{{pgPrev}}" style="opacity: {{ppo}};">‹ Previous</span><span class="mu" style="font-size: 13px;">{{pgLbl}}</span><span class="btn b-sm" onClick="{{pgNext}}" style="opacity: {{pno}};">Next ›</span></div></sc-if></div></sc-if><sc-if value="{{modeDel}}" hint-placeholder-val="{{ false }}"><div class="agenda"><div style="display: flex; justify-content: space-between; align-items: baseline;"><strong style="font-size: 17px;">{{delLbl}}</strong><span class="mu" style="font-size: 12px;">Everything you approved, and where it went live</span></div>
<sc-if value="{{dPrevw}}" hint-placeholder-val="{{ false }}"><div class="dprev"><span>Preview of what <b>{{vName}}</b> delivers each month. You are on {{curName}}.</span><a href="Upgrade.dc.html" class="btn b-sm b-coral">Upgrade to {{vName}}</a></div></sc-if><div class="dch"><sc-for list="{{chans}}" as="c" hint-placeholder-count="7"><span class="chip {{c.cls}}" onClick="{{c.pick}}">{{c.n}}<b>{{c.k}}</b></span></sc-for></div>
<sc-for list="{{dmon}}" as="g" hint-placeholder-count="2"><div style="display: flex; flex-direction: column; gap: 8px;"><span class="dayh">{{g.m}}<span class="mu" style="font-weight: 500;">{{g.c}} delivered</span></span><sc-for list="{{g.items}}" as="i" hint-placeholder-count="3"><div class="itm2"><div class="row" style="padding: 11px 14px;"><span class="bar2" style="background: {{i.c}};"></span><span class="tt"><strong style="font-size: 14px;">{{i.t}}</strong><span>{{i.ty}} · {{i.dest}}</span></span><span class="dch-ch">{{i.ch}}</span><span class="pill {{i.pc}}">{{i.st}}</span><span class="dlink"><span class="dicon" style="display: {{i.docd}};"><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M6 3h9l4 4v14H6z"/><path d="M9 12h7M9 16h7M9 8h3"/></svg></span>{{i.go}}</span></div></div></sc-for></div></sc-for>
<sc-if value="{{dEmpty}}" hint-placeholder-val="{{ false }}"><div class="emp">Nothing delivered here yet.</div></sc-if>
<sc-if value="{{dShowPg}}" hint-placeholder-val="{{ true }}"><div style="display: flex; justify-content: space-between; align-items: center; padding-top: 4px;"><span class="rpa" onClick="{{dPrev}}" style="opacity: {{dpo}};">‹</span><span class="mu" style="font-size: 12px;">{{dPgLbl}}</span><span class="rpa" onClick="{{dNext}}" style="opacity: {{dno}};">›</span></div></sc-if></div></sc-if></div></div>"""
pjs = DATA + r"""    IT.forEach((x, i) => x.id = i);
    const cur = tier, view = S.view === undefined ? cur : S.view;
    const off = S.off || {};
    const need = x => TC[x.k][3];
    const vis = IT.filter(x => need(x) <= view && !off[x.k]);
    const allM = S.all === undefined ? true : S.all, selD = S.day === undefined ? 6 : S.day;
    const mcal = Array.from({ length: 35 }, (_, i) => { const n = i - 3; const inM = n >= 1 && n <= 31; const ds = inM ? IT.filter(x => x.d === n && !off[x.k]).sort((a, b) => need(a) - need(b)) : []; const seen = {}; const dots = []; ds.forEach(x => { if (!seen[x.k] && dots.length < 8) { seen[x.k] = 1; dots.push({ c: TC[x.k][2], k: need(x) > cur ? 'lk' : '' }); } }); return { n: inM ? String(n) : '', cls: (inM ? '' : 'off') + (inM && n === selD && !allM ? ' on' : ''), dots, pick: () => { if (inM) this.setState({ day: n, all: false, open: undefined, pg: 0 }); } }; });
    const status = x => { if (need(x) > cur) return ['p-lk', '🔒 ' + TN[need(x)]]; if ((S.rw || {})[x.id]) return ['p-rw', 'Rewriting']; if ((S.ok || {})[x.id] || S.okAll) return ['p-ok', 'Approved']; return x.d <= 9 ? ['p-ap', 'Needs approval'] : ['p-sc', 'Scheduled']; };
    const rows = (allM ? vis : vis.filter(x => x.d === selD)).slice().sort((a, b) => a.d - b.d || need(a) - need(b));
    const DN = ['Thursday', 'Friday', 'Saturday', 'Sunday', 'Monday', 'Tuesday', 'Wednesday'];
    const PG = 12; const nPg = Math.max(1, Math.ceil(rows.length / PG)); const pg = Math.min(S.pg || 0, nPg - 1); const pRows = rows.slice(pg * PG, pg * PG + PG);
    const days = [...new Set(pRows.map(x => x.d))].map(d => { const its = pRows.filter(x => x.d === d); return { d: 'Oct ' + d, n: DN[(d - 1) % 7], c: String(its.length), items: its.map(x => { const st = status(x); const locked = need(x) > cur; const open = S.open === x.id; return { t: locked ? TC[x.k][1] : x.t, ty: locked ? 'Included in ' + TN[need(x)] : TC[x.k][1], c: TC[x.k][2], dest: locked ? 'Upgrade to see it' : x.dest, body: x.body, img: x.img, imd: x.img ? 'flex' : 'none', st: st[1], pc: st[0], lk: locked ? 'lockd' : '', open, car: open ? '▲' : '▼', act: !locked, locked, tn: TN[need(x)], pick: () => this.setState({ open: open ? undefined : x.id }), approve: () => { const o = Object.assign({}, S.ok); o[x.id] = true; this.setState({ ok: o }); }, rewrite: () => { const r = Object.assign({}, S.rw); r[x.id] = true; this.setState({ rw: r, noteTxt: '' }); } }; }) }; });
    const groups = [1, 2, 3].map(g => ({ n: TN[g] + (g > cur ? ' · 🔒 upgrade' : ''), types: TY.filter(y => y[3] === g).map(y => ({ n: y[1], c: y[2], k: y[3] > cur ? '🔒' : String(IT.filter(x => x.k === y[0]).length), cls: off[y[0]] || y[3] > cur ? 'offt' : '', pick: () => { const o = Object.assign({}, off); o[y[0]] = !o[y[0]]; this.setState({ off: o }); } })) }));
    const tabs = TN.map((n, i) => ({ n, cd: i === cur ? 'inline' : 'none', cls: i === view ? 'on' : '', pick: () => this.setState({ view: i, open: undefined, pg: 0 }) }));
    // chart
    const MON = [['Mar 2026', 'Mar', 30], ['Apr 2026', 'Apr', 31], ['May 2026', 'May', 32], ['Jun 2026', 'Jun', 40], ['Jul 2026', 'Jul', 45], ['Aug 2026', 'Aug', 51], ['Sep 2026', 'Sep', 55], ['Oct 2026', 'Oct', 58]];
    const WK = [['Sep 3', 'Sep 3', 55], ['Sep 10', 'Sep 10', 56], ['Sep 17', 'Sep 17', 56], ['Sep 24', 'Sep 24', 57], ['Oct 1', 'Oct 1', 58]];
    const TF = [['1M', WK], ['3M', MON.slice(-4)], ['6M', MON.slice(-6)], ['YTD', MON], ['All', MON]];
    const tf = S.tf === undefined ? 3 : S.tf; const data = TF[tf][1]; const weekly = tf === 0;
    const pr = [58, 63, 72, 80][view];
    const FC = weekly ? [] : [['Dec', 58 + (pr - 58) * 0.4], ['Jan', 58 + (pr - 58) * 0.7], ['Mar', pr]];
    const nX = data.length + FC.length; const xs = i => 60 + i * (530 / Math.max(1, nX - 1));
    const lo = 20, hi = 90; const ys = v => (150 - (v - lo) * (140 / (hi - lo))).toFixed(1);
    const selM = S.rep === undefined ? 'Oct 2026' : S.rep;
    const pts = data.map((d, i) => ({ x: xs(i).toFixed(1), y: ys(d[2]), l: d[1], r: d[0] === selM ? 6 : 4, c: d[0] === selM ? '#13203a' : '#2b59d9', pick: () => { if (!weekly) this.setState({ rep: d[0] }); } }));
    const line = pts.map(p => p.x + ',' + p.y).join(' ');
    const area = line + ' ' + pts[pts.length - 1].x + ',150 ' + pts[0].x + ',150';
    const fline = FC.length ? [pts[pts.length - 1].x + ',' + pts[pts.length - 1].y].concat(FC.map((f, j) => xs(data.length + j).toFixed(1) + ',' + ys(f[1]))).join(' ') : '';
    const flabs = FC.map((f, j) => ({ x: xs(data.length + j).toFixed(1), l: f[0] }));
    const grid = [30, 50, 70, 90].map(v => ({ y: ys(v), ty: (+ys(v) + 3).toFixed(1), v: String(v) }));
    const mi = MON.findIndex(m => m[0] === selM); const sv = MON[mi][2], pv = mi > 0 ? MON[mi - 1][2] : sv;
    const rp = S.rp || 0; const repsAll = MON.slice().reverse().map((m, k) => { const i = MON.length - 1 - k; const ch = i > 0 ? m[2] - MON[i - 1][2] : 0; return { m: m[0], s: String(m[2]), ch: i > 0 ? '+' + ch : 'first', cls: m[0] === selM ? 'on' : '' }; }); const nRp = Math.ceil(repsAll.length / 3); const reps = repsAll.slice(rp * 3, rp * 3 + 3);
    const P = [['best med spa in Irvine', '2,900', ''], ['natural lip filler Irvine', '1,300', ''], ['Botox Irvine price', '2,400', 'Coastline Med Spa'], ['best lip filler Orange County', '1,900', 'Coastline Med Spa'], ['Morpheus8 body near me', '1,100', 'Glow Bar Irvine']];
    const cc = v => v === 'No' ? 'n' : 'y';
    const prompts = P.map(p => ({ q: p[0], v: p[1], who: p[2] ? 'No, names ' + p[2] : 'Yes', c: p[2] ? 'n' : 'y' }));
    const CHN = { ds: 'Directories', rd: 'Reviews', rr: 'Reviews', qa: 'Local AI Registry', pr: 'Press', mc: 'Website', gp: 'Google profile', go: 'Google profile', rl: 'Google profile', rv: 'Google profile', tf: 'Technical', sp: 'Technical', ur: 'Technical', tm: 'Technical', sc: 'Website', cn: 'Technical', em: 'Technical', ar: 'Website', bl: 'Website', nb: 'Press' };
    const GOL = { Directories: 'View listing', Reviews: 'View reply', 'Local AI Registry': 'View answer', Press: 'View story', Website: 'View page', 'Google profile': 'View on Google', Technical: 'Open the Google Doc' };
    const mode = S.mode || 'cal';
    const dv = Math.max(cur, view); const dPrevw = view > cur;
    const okd = IT.filter(x => need(x) <= cur && ((S.ok || {})[x.id] || S.okAll)).sort((a, b) => b.d - a.d).map(x => ({ x, when: 'Oct ' + x.d, mon: 'October 2026', live: false }));
    const past = [];
    [['September 2026', 'Sep', 30], ['August 2026', 'Aug', 31]].forEach(([mn, ab, nd], j) => IT.filter(x => need(x) <= dv && x.d <= nd && !(j > 0 && x.k === 'ds')).slice().sort((a, b) => b.d - a.d).forEach(x => past.push({ x, when: ab + ' ' + x.d, mon: mn, live: true })));
    const allDel = okd.concat(past);
    const CHS = ['All', 'Website', 'Technical', 'Google profile', 'Directories', 'Reviews', 'Local AI Registry', 'Press'];
    const dch = S.dch || 'All';
    const dRows = allDel.filter(r => dch === 'All' || CHN[r.x.k] === dch);
    const chans = CHS.map(c => ({ n: c, k: String(c === 'All' ? allDel.length : allDel.filter(r => CHN[r.x.k] === c).length), cls: c === dch ? 'on' : '', pick: () => this.setState({ dch: c, dpg: 0 }) }));
    const DPG = 12; const dnPg = Math.max(1, Math.ceil(dRows.length / DPG)); const dpg = Math.min(S.dpg || 0, dnPg - 1); const dP = dRows.slice(dpg * DPG, dpg * DPG + DPG);
    const dmon = [...new Set(dP.map(r => r.mon))].map(m => { const its = dP.filter(r => r.mon === m); return { m, c: String(dRows.filter(r => r.mon === m).length), items: its.map(r => ({ t: r.x.t, ty: TC[r.x.k][1], c: TC[r.x.k][2], ch: CHN[r.x.k], st: r.live ? 'Delivered ' + r.when : 'Approved, live ' + r.when, pc: r.live ? 'p-dl' : 'p-ok', go: r.live ? GOL[CHN[r.x.k]] + ' ⟶' : '', docd: CHN[r.x.k] === 'Technical' ? 'inline-flex' : 'none', dest: CHN[r.x.k] === 'Technical' ? 'Report in Google Docs' : r.x.dest })) }; });
    const nAp = vis.filter(x => status(x)[0] === 'p-ap').length;
    return Object.assign(base, { tabs, mcal, dowS: ['S', 'M', 'T', 'W', 'T', 'F', 'S'], groups, days, nAll: String(vis.length), nOn: String(vis.filter(x => need(x) <= cur).length), vName: TN[view], nAp: String(nAp), canAct: cur > 0 && nAp > 0, emptyM: view === 0,
      rangeLbl: (allM ? 'Deliverables · October' : 'Deliverables · October ' + selD) + ' · ' + rows.length, showAll: () => this.setState({ all: true, open: undefined, pg: 0 }), approveAll: () => this.setState({ okAll: true }),
      noteTxt: S.noteTxt || '', onNote: (e) => this.setState({ noteTxt: e.target.value }),
      ctaT: view === cur ? 'You are on ' + TN[cur] : (view > cur ? (vis.length - IT.filter(x => need(x) <= cur).length) + ' more pieces a month, locked' : ''), ctaOn: view !== cur && view > 0, ctaB: view > cur ? 'Upgrade to ' + TN[view] : 'Switch to ' + TN[view],
      proj: String(pr), pgLbl: 'Page ' + (pg + 1) + ' of ' + nPg, pgPrev: () => this.setState({ pg: Math.max(0, pg - 1), open: undefined }), pgNext: () => this.setState({ pg: Math.min(nPg - 1, pg + 1), open: undefined }), ppo: pg > 0 ? '1' : '0.35', pno: pg < nPg - 1 ? '1' : '0.35', showPg: nPg > 1, xl: weekly ? 'Week' : 'Month, Mar 2026 to Mar 2027 forecast', repPg: (rp + 1) + ' of ' + nRp, repPrev: () => this.setState({ rp: Math.max(0, rp - 1) }), repNext: () => this.setState({ rp: Math.min(nRp - 1, rp + 1) }), rpo: rp > 0 ? '1' : '0.35', rno: rp < nRp - 1 ? '1' : '0.35', tfs: TF.map((f, i) => ({ n: f[0], cls: i === tf ? 'on' : '', pick: () => this.setState({ tf: i }) })), pts, line, area, fline, flabs, grid, reps, selRep: selM, prompts,
      dPrevw: mode === 'del' && dPrevw, curName: TN[cur], modeCal: mode === 'cal', modeDel: mode === 'del', m1c: mode === 'cal' ? 'on' : '', m2c: mode === 'del' ? 'on' : '', setM1: () => this.setState({ mode: 'cal' }), setM2: () => this.setState({ mode: 'del' }), nDel: String(allDel.length), chans, dmon, dEmpty: dRows.length === 0, delLbl: 'Approved and delivered · ' + (dch === 'All' ? 'everything' : dch) + ' · ' + dRows.length, dShowPg: dnPg > 1, dPgLbl: 'Page ' + (dpg + 1) + ' of ' + dnPg, dPrev: () => this.setState({ dpg: Math.max(0, dpg - 1) }), dNext: () => this.setState({ dpg: Math.min(dnPg - 1, dpg + 1) }), dpo: dpg > 0 ? '1' : '0.35', dno: dpg < dnPg - 1 ? '1' : '0.35',
      hv: String(sv), hch: mi > 0 ? '+' + (sv - pv) + ' vs last month' : '', hl: selM === 'Oct 2026' ? 'today' : selM });"""
build('OwnerPremium.dc.html','work','Premium',prem,pjs,tier0=2)
