import sys; sys.path.insert(0,'/tmp/gen')
src=open('/tmp/gen/story.py').read(); exec(src[:src.index('# ---------- REPORT')])
CSS2=CSS+r'''.em{border:1px solid #e4ded2;border-radius:14px;overflow:hidden;background:#ffffff}
.em .eh{padding:10px 14px;background:#f7f4ee;font-size:12px;color:#667085;display:flex;flex-direction:column;gap:2px}
.em .eh b{color:#13203a;font-size:13px}
.em .eb{padding:14px;font-size:13px;line-height:20px;color:#3d4658;display:flex;flex-direction:column;gap:10px}
.qa{padding:12px;border-radius:12px;border:1px solid #ebebeb;display:flex;flex-direction:column;gap:6px;font-size:13px;line-height:19px}
.un{font-size:12px;font-weight:700;color:#13203a}.un i{font-style:normal;font-weight:500;color:#8a8a8a}
.tg{display:inline-flex;height:20px;padding:0 8px;border-radius:10px;font-size:10px;font-weight:700;letter-spacing:0.06em;text-transform:uppercase;align-items:center;background:#efeae0;color:#667085}
.gbtn{height:44px;border-radius:22px;border:1px solid #dcd5c7;display:flex;align-items:center;justify-content:center;gap:10px;font-size:14px;font-weight:600;background:#ffffff}
.lst{display:flex;flex-direction:column}.lst .it{display:flex;justify-content:space-between;align-items:center;gap:10px;padding:10px 0;border-bottom:1px solid #f0ebe1;font-size:13px}
'''
def board(fn,title,back,flows):
    B=header(back)+f'<div class="wrap">{"".join(flows)}</div>'
    open(P+fn,'w').write(page(title,CSS2,B,'    return {};')); print(fn)
BK=lambda h,t:f'<a href="{h}" class="btn b-sm">{t}</a>'
G='<span style="font-weight: 800; color: #4285f4;">G</span>'

# ---- POST (not signed in) + sign in
board('Post.dc.html','Posting',BK('Explore.dc.html','Back to Explore'),[flow('Anyone can post','No account, no code, no contact info needed. Leaving an email or mobile is optional, only to hear back when someone replies.',[
frame('1','Tap Post, write','''<div class="mh"><strong>Post about Lumen Aesthetics</strong><span class="x">✕</span></div><div class="chips"><span class="chip on">Question</span><span class="chip">Tip</span><span class="chip">Heads-up</span></div><div class="inp ta focus">Does Dr. Nair do the lip filler herself or a nurse?</div><div class="fl"><label>Add detail <span class="mu" style="font-weight: 400;">(optional)</span></label><div class="inp ta">First time, want it subtle.</div></div><div class="fl"><label>How do you know Lumen?</label><div class="chips"><span class="chip">I went</span><span class="chip">Going soon</span><span class="chip on">Researching</span></div></div><span class="btn b-dark" style="margin-top: auto;">Post</span>'''),
frame('2','Want to hear back?','''<div class="mh"><strong>Posted as irvine_regular_42</strong><span class="x">✕</span></div><div class="okb">Your question is live. It has its own link and Lumen was told.</div><div class="fl"><label>Get notified when someone replies <span class="mu" style="font-weight: 400;">(optional)</span></label><div class="inp focus">maya.t@gmail.com</div><span class="mu" style="font-size: 12px;">Email or mobile. We only use it to tell you about replies.</span></div><span class="btn b-dark" style="margin-top: auto;">Notify me</span><span class="btn">No thanks</span>'''),
frame('3','Someone replies','''<div class="em"><div class="eh"><b>Lumen answered your question</b>To maya.t@gmail.com</div><div class="eb"><span><strong>Lumen Aesthetics (owner):</strong> "Dr. Nair does every lip filler herself. Consults are $75, credited if you book."</span><span class="btn b-sm b-dark" style="align-self: flex-start;">See the answer</span></div></div><div class="note">Want a username that is yours, and credit for fixes? Save it with a password when you come back.</div>'''),
frame('4','Coming back: sign in','''<strong style="font-size: 26px; font-family: 'Cormorant Garamond', Georgia, serif; font-weight: 500;">Sign in to your record.</strong><div class="fl"><label>Email</label><div class="inp"></div></div><div class="fl"><label>Password <a href="#" style="float: right; font-weight: 400;">Forgot it?</a></label><div class="inp"></div></div><a href="SignIn.dc.html" class="btn b-dark">Sign in</a><div class="gbtn">Sign in with Google</div>''')],4)])

# ---- SEARCH
board('Search.dc.html','Search results',BK('Home.dc.html','Back to home'),[flow('Search','One box on the homepage and in the header. It finds businesses, types and cities.',[
frame('1','Typing','''<div class="inp focus">lumen</div><div class="lst"><span class="mu" style="font-size: 11px; font-weight: 700; padding-top: 6px;">BUSINESSES</span><div class="it"><span><strong>Lumen Aesthetics</strong><br><span class="mu">Med spa · Irvine Spectrum</span></span><span class="mu">22 posts</span></div><div class="it"><span><strong>Lumen Dental Studio</strong><br><span class="mu">Dentist · Tustin</span></span><span class="mu">3 posts</span></div><span class="mu" style="font-size: 11px; font-weight: 700; padding-top: 10px;">TYPES</span><div class="it"><span>Med spas in Irvine</span><span>›</span></div></div>'''),
frame('2','Several matches','''<strong style="font-size: 16px;">3 results for "glow"</strong><div class="lst"><div class="it"><span><strong>Glow Bar Irvine</strong><br><span class="mu">Med spa · Woodbridge · 41 posts</span></span><span class="btn b-sm">Open</span></div><div class="it"><span><strong>Glow Nail Lounge</strong><br><span class="mu">Nail salon · Irvine · 12 posts</span></span><span class="btn b-sm">Open</span></div><div class="it"><span><strong>Glow Skin Studio</strong><br><span class="mu">Esthetician · Costa Mesa · 2 posts</span></span><span class="btn b-sm">Open</span></div></div><span class="mu" style="font-size: 12px;">Sorted by how close and how active. <a href="Explore.dc.html">See them on the map</a></span>'''),
frame('3','Typo','''<strong style="font-size: 16px;">No results for "lumin asthetics"</strong><div class="note">Did you mean <a href="Main.dc.html"><strong>Lumen Aesthetics</strong></a>, Irvine Spectrum?</div>'''),
frame('4','Not on the registry yet','''<strong style="font-size: 16px;">No results for "Bloom Wellness Tustin"</strong><div class="lst"><div class="it"><span><strong>Is it your business?</strong><br><span class="mu">Add it and claim it in 2 minutes.</span></span><a href="AddBiz.dc.html" class="btn b-sm b-coral">Add it</a></div><div class="it"><span><strong>Just looking for it?</strong><br><span class="mu">Ask locals in Tustin.</span></span><a href="Post.dc.html" class="btn b-sm">Ask</a></div></div>''')],4)])

# ---- BOOK (Yelp-style fan out + OrbitBack)
board('Book.dc.html','Booking requests',BK('Main.dc.html','Back to Lumen'),[flow('Request a booking','Like Yelp: the same request can go to similar places nearby, so the visitor hears back fast.',[
frame('1','Request from Lumen\'s page','''<div class="mh"><strong>Request a booking at Lumen</strong><span class="x">✕</span></div><div class="fl"><label>What for?</label><div class="chips"><span class="chip on">Lip filler</span><span class="chip">Botox</span><span class="chip">Consult</span><span class="chip">Other</span></div></div><div class="fl"><label>When works?</label><div class="chips"><span class="chip on">This week</span><span class="chip on">Weekday mornings</span><span class="chip">Weekends</span></div></div><div class="fl"><label>Anything they should know?</label><div class="inp ta">First time. Subtle, please.</div></div><div class="fl"><label>Name, email and mobile</label><div class="inp">Anna Park · anna.park22@gmail.com · (714) 555-0132</div></div><span class="btn b-dark" style="margin-top: auto;">Next</span>'''),
frame('2','Also ask nearby places?','''<div class="mh"><strong>Hear back faster</strong><span class="x">✕</span></div><span style="font-size: 14px; color: #3d4658;">Send the same request to similar places nearby. You pick who you go with.</span><div class="opt on"><span class="rdo"></span><span><strong>Lumen Aesthetics</strong><br><span class="mu">Your pick · usually replies in 2 hours</span></span></div><div class="opt on"><span class="rdo"></span><span><strong>Coastline Med Spa</strong><br><span class="mu">0.8 mi · lip filler from $650</span></span></div><div class="opt on"><span class="rdo"></span><span><strong>Glow Bar Irvine</strong><br><span class="mu">1.4 mi · lip filler from $599</span></span></div><div class="opt"><span class="rdo"></span><span><strong>Spectrum Aesthetics MD</strong><br><span class="mu">2.1 mi</span></span></div><span class="btn b-dark" style="margin-top: auto;">Send to 3</span>'''),
frame('3','Replies come in','''<strong style="font-size: 16px;">Your request · lip filler</strong><div class="lst"><div class="it"><span><strong>Lumen Aesthetics</strong><br><span class="mu">Thu 10:30 AM with Dr. Nair · $75 consult credited</span></span><span class="btn b-sm b-dark">Book</span></div><div class="it"><span><strong>Coastline Med Spa</strong><br><span class="mu">Wed 2:00 PM · $650</span></span><span class="btn b-sm">Book</span></div><div class="it"><span><strong>Glow Bar Irvine</strong><br><span class="mu">No reply yet</span></span><span class="mu">·</span></div></div><span class="mu" style="font-size: 12px;">We email and text you as each place replies.</span>'''),
frame('4','Booked','''<div class="big"><span class="ic" style="background: #e8f5ea; color: #237233;">✓</span><strong style="font-size: 20px;">Booked at Lumen</strong><span style="font-size: 14px; color: #3d4658;">Thursday, Oct 8, 10:30 AM with Dr. Nair</span></div><div class="note">We sent a confirmation to anna.park22@gmail.com and a text reminder the day before. Coastline and Glow Bar were told you booked elsewhere.</div>'''),
frame('5','What Lumen sees','''<div class="qa"><span class="un">anna_irvine_22 <i>· Booking request · 12 min ago</i></span><strong>Lip filler · this week, weekday mornings</strong><span class="mu">Anna Park · anna.park22@gmail.com · (714) 555-0132</span><div class="warn">Also sent to 2 places nearby. The first good reply usually wins.</div><span style="display: flex; gap: 6px;"><span class="btn b-sm b-dark">Offer a time</span><span class="btn b-sm">Decline</span></span></div>''')])])

# ---- CONSUMER NOTIFICATIONS + badge
board('Notify.dc.html','Notifications for locals',BK('Me.dc.html','Back to your profile'),[flow('What locals hear back','Every notification opens signed in, one tap, no password.',[
frame('1','In the app','''<div class="mh"><strong>Notifications</strong><span class="x">✕</span></div><div class="lst"><div class="it"><span><strong>Lumen accepted your fix</strong><br><span class="mu">Parking is Structure B, level 3. You are now a Local expert.</span></span><span class="mu">2h</span></div><div class="it"><span><strong>Your tip is what ChatGPT says now</strong><br><span class="mu">"Ask for level 3" · 1,240 people saw it</span></span><span class="mu">1d</span></div><div class="it"><span><strong>New answer on your question</strong><br><span class="mu">oc_skin_nerd answered about Morpheus8</span></span><span class="mu">2d</span></div><div class="it"><span><strong>Coastline replied to your booking</strong><br><span class="mu">Wed 2:00 PM</span></span><span class="mu">3d</span></div></div>'''),
frame('2','Local expert badge','''<div class="big"><span class="ic" style="background: #e8eefc; color: #2b59d9;">★</span><strong style="font-size: 20px;">You are a Local expert</strong><span style="font-size: 14px; line-height: 21px; color: #3d4658;">Lumen's owner accepted your suggested change. The fact on the page now shows your name as the source.</span></div><div class="note"><strong>How the badge works.</strong> You earn it the first time a business owner accepts a change you suggested. Each accepted change adds to your count.</div><span class="btn b-dark" style="margin-top: auto;">See your profile</span>'''),
frame('3','Email settings','''<div class="mh"><strong>Email me when</strong><span class="x">✕</span></div><div class="row"><span>Someone answers me</span><span>On</span></div><div class="row"><span>A business accepts my fix</span><span>On</span></div><div class="row"><span>My tip is what AI says</span><span>On</span></div><div class="row"><span>Booking replies</span><span>Email and text</span></div>''')])])

# ---- MODERATION
board('Moderation.dc.html','Reporting a post',BK('Main.dc.html','Back to Lumen'),[flow('Reporting a post','Anyone can report. Owners cannot delete posts about them, they can report and reply.',[
frame('1','Report a post','''<div class="mh"><strong>Report this post</strong><span class="x">✕</span></div><div class="opt"><span class="rdo"></span>Not true, I can show why</div><div class="opt on"><span class="rdo"></span>Spam or an ad</div><div class="opt"><span class="rdo"></span>Rude, hateful or harassing</div><div class="opt"><span class="rdo"></span>Private info, like a phone number or health details</div><div class="opt"><span class="rdo"></span>Posted by the business or a competitor</div><span class="btn b-dark" style="margin-top: auto;">Report</span>'''),
frame('2','Guidelines, short','''<strong style="font-size: 16px;">Community guidelines</strong><div class="lst"><div class="it"><span>Say what you saw, heard or paid.</span></div><div class="it"><span>Say how you know: went, called, work there.</span></div><div class="it"><span>No private details about anyone.</span></div><div class="it"><span>Owners answer, they don't delete.</span></div><div class="it"><span>No paid or fake posts. Accounts that do this are removed.</span></div></div>'''),
frame('3','What the poster sees if removed','''<div class="em"><div class="eh"><b>We removed one of your posts</b>To lip_deal_4u</div><div class="eb"><span>Your post on Glow Bar Irvine was removed as an ad. Posts need to be about your own experience.</span><span class="mu">Think we got it wrong? <a href="#">Ask for a second look</a></span></div></div>'''),
frame('4','Owner reports a post about them','''<div class="qa"><span class="un">front_desk_fail <i>· Heads-up</i></span><strong>They double-booked me and charged a no-show fee.</strong></div><div class="note"><strong>You can't delete this.</strong> Reply publicly, or report it if it is not true. A reply ranks first and is what AI will repeat.</div><span style="display: flex; gap: 6px;"><span class="btn b-sm b-dark">Reply</span><span class="btn b-sm">Report</span></span>''')],4)])

# ---- ADD BUSINESS
board('AddBiz.dc.html','Add a business',BK('Search.dc.html','Back to search'),[flow('Business not on the registry','Add it, then claim it in the same flow.',[
frame('1','Add it','''<div class="mh"><strong>Add a business</strong><span class="x">✕</span></div><div class="fl"><label>Business name</label><div class="inp focus">Bloom Wellness</div></div><div class="fl"><label>Address</label><div class="inp">17 Main St, Tustin, CA 92780</div></div><div class="fl"><label>Type</label><div class="inp">Med spa</div></div><div class="fl"><label>Website</label><div class="inp">bloomwellnesstustin.com</div></div><div class="opt on"><span class="rdo"></span>This is my business</div><span class="btn b-dark" style="margin-top: auto;">Add it</span>'''),
frame('2','We fill in what we can find','''<strong style="font-size: 16px;">We found 23 facts about Bloom Wellness</strong><div class="lst"><div class="it"><span><span class="mk mk-site"></span>Phone (714) 555-0199</span><span class="mu">Website</span></div><div class="it"><span><span class="mk mk-site"></span>Tue to Sat, 10 to 7</span><span class="mu">Website</span></div><div class="it"><span><span class="mk mk-ai"></span>Offers Botox and HydraFacial</span><span class="mu">AI guess</span></div></div><span class="btn b-coral" style="margin-top: auto;">Claim it now</span>'''),
frame('3','Claim continues as usual','''<div class="big"><span class="ic" style="background: #e8f5ea; color: #237233;">✓</span><strong style="font-size: 20px;">Bloom Wellness is on the registry</strong><span style="font-size: 14px; color: #3d4658;">Next: your work email and mobile, then a text code.</span></div><a href="Claim.dc.html" class="btn b-dark">Continue to claim</a>''')])])

# ---- CLAIM PROBLEMS
board('ClaimIssue.dc.html','When a claim does not go through',BK('Claim.dc.html','Back to claim'),[flow('Claim problems','Two things go wrong: we can\'t match you, or someone already claimed the page.',[
frame('1','We could not match you','''<div class="mh"><strong>Let's prove it another way</strong><span class="x">✕</span></div><span style="font-size: 14px; color: #3d4658;">Your mobile does not match the phone on Lumen's listings. Pick one:</span><div class="opt on"><span class="rdo"></span><span><strong>Call me on the business line</strong><br><span class="mu">We call (949) 555-0148 with a code. 1 minute.</span></span></div><div class="opt"><span class="rdo"></span><span><strong>Connect Google Business Profile</strong><br><span class="mu">Instant if you manage it.</span></span></div><div class="opt"><span class="rdo"></span><span><strong>Upload a document</strong><br><span class="mu">Business license or utility bill. 1 business day.</span></span></div>'''),
frame('2','Document review','''<div class="big"><span class="ic" style="background: #fff1e0; color: #e8740c;">⏳</span><strong style="font-size: 20px;">We're checking it</strong><span style="font-size: 14px; color: #3d4658;">Usually within 1 business day. You can finish setup now. Nothing goes public until you're approved.</span></div><a href="Setup.dc.html" class="btn b-dark">Finish setup while you wait</a>'''),
frame('3','Already claimed','''<div class="mh"><strong>Lumen Aesthetics is already claimed</strong><span class="x">✕</span></div><span style="font-size: 14px; color: #3d4658;">Someone at Lumen claimed it on Aug 2 with a lumenirvine.com email.</span><div class="opt on"><span class="rdo"></span><span><strong>Ask them to add me</strong><br><span class="mu">We email the owner. They add you to the team.</span></span></div><div class="opt"><span class="rdo"></span><span><strong>I'm the owner and didn't claim it</strong><br><span class="mu">Open a dispute. The page locks while we check.</span></span></div>'''),
frame('4','Dispute opened','''<div class="warn"><strong>Page locked for review.</strong> No one can edit Lumen's page until we confirm the owner, usually in 2 business days.</div><div class="lst"><div class="it"><span>Upload proof of ownership</span><span class="btn b-sm">Upload</span></div><div class="it"><span>We contact the current claimant</span><span class="mu">Today</span></div><div class="it"><span>Decision by email</span><span class="mu">Oct 1</span></div></div>''')],4)])

# ---- GOOGLE VERIFY
board('Verify.dc.html','Verify ownership with Google',BK('OwnerHome.dc.html','Back to dashboard'),[flow('Verify with Google Business Profile','Step 4 of setup. We read your listing to verify you. We change nothing on Google until you start a plan and approve it.',[
frame('1','From the dashboard','''<strong style="font-size: 16px;">Verify you own Lumen</strong><span style="font-size: 14px; line-height: 21px; color: #3d4658;">Connect the Google account that manages Lumen's Business Profile.</span><div class="gbtn">'''+G+''' Connect Google Business Profile</div><div class="note">We won't touch your Google listing until you sign up for a plan and approve each change.</div>'''),
frame('2','Google sign-in','''<div style="text-align: center; font-size: 20px;">'''+G+'''</div><strong style="font-size: 16px; text-align: center;">Local AI Registry wants to</strong><div class="lst"><div class="it"><span>See your Business Profile locations</span><span>✓</span></div><div class="it"><span>See reviews and questions</span><span>✓</span></div><div class="it"><span>Post updates and replies, only after you approve</span><span>✓</span></div></div><span class="btn b-dark" style="margin-top: auto;">Allow</span>'''),
frame('3','Pick the location','''<strong style="font-size: 16px;">Which location is this?</strong><div class="opt on"><span class="rdo"></span><span><strong>Lumen Aesthetics</strong><br><span class="mu">71 Fortune Dr, Irvine · matches</span></span></div><div class="opt"><span class="rdo"></span><span><strong>Lumen Aesthetics Newport</strong><br><span class="mu">Add as a second location</span></span></div><span class="btn b-dark" style="margin-top: auto;">Verify</span>'''),
frame('4','Something does not match','''<div class="warn"><strong>Your Google hours differ.</strong> Google says Mon 9 to 6. You confirmed closed Mondays.</div><div class="opt on"><span class="rdo"></span>Keep closed Mondays (we fix Google once you're on a plan)</div><div class="opt"><span class="rdo"></span>Google is right, update my page</div>'''),
frame('5','Verified','''<div class="big"><span class="ic" style="background: #e8f5ea; color: #237233;">✓</span><strong style="font-size: 20px;">Lumen is fully verified</strong><span style="font-size: 14px; color: #3d4658;">Your page now shows "Verified owner." 612 reviews and 18 questions synced.</span></div><a href="OwnerPremium.dc.html" class="btn b-coral">See what we would fix</a>''')],5)])

# ---- INVITE ACCEPT
board('Invite.dc.html','Accepting a team invite',BK('OwnerSettings.dc.html','Back to settings'),[flow('Joining a team','What Lumen\'s marketing person sees after Dr. Nair invites them.',[
frame('1','The invite email','''<div class="em"><div class="eh"><b>Dr. Priya Nair invited you to Lumen Aesthetics</b>To jess@lumenirvine.com</div><div class="eb"><span>You're invited as <strong>Marketing</strong> on Local AI Registry. You'll approve the work that goes out under Lumen's name and reply to locals.</span><span class="btn b-sm b-dark" style="align-self: flex-start;">Join Lumen</span></div></div>'''),
frame('2','Confirm who you are','''<div class="mh"><strong>Join Lumen Aesthetics</strong><span class="x">✕</span></div><div class="fl"><label>Your name</label><div class="inp">Jess Kim</div></div><div class="fl"><label>Your mobile, for sign-in codes</label><div class="inp focus">(949) 555-0172</div></div><div class="note">Role: Marketing. Approves work and edits the page. Can't see billing.</div><span class="btn b-dark" style="margin-top: auto;">Send my code</span>'''),
frame('3','First thing they see','''<strong style="font-size: 16px;">Welcome, Jess</strong><div class="okb"><strong>3 pieces are waiting for you.</strong> Two Google posts and a press release for Morpheus8 Body.</div><div class="lst"><div class="it"><span>Google post: Morpheus8 Body is here</span><span class="btn b-sm b-dark">Review</span></div><div class="it"><span>Reply to 4 new reviews</span><span class="btn b-sm">Review</span></div><div class="it"><span>2 questions from locals</span><span class="btn b-sm">Answer</span></div></div>''')])])

# ---- EMAILS
board('Emails.dc.html','Owner emails',BK('OwnerHome.dc.html','Back to dashboard'),[flow('Emails owners get','Every button opens the exact item, signed in, no password.',[
frame('1','Claim confirmed','''<div class="em"><div class="eh"><b>Lumen Aesthetics is yours</b>From Local AI Registry</div><div class="eb"><span>You claimed Lumen's page. AI gets 3 facts wrong about you today. One step left: verify with Google.</span><span class="btn b-sm b-dark" style="align-self: flex-start;">Finish setup</span></div></div>'''),
frame('2','Approvals needed','''<div class="em"><div class="eh"><b>3 pieces need your approval</b>Due before they go out Tuesday</div><div class="eb"><span>• Google post: Morpheus8 Body is here<br>• Reply to Aisha M.'s review<br>• Press release: Irvine's first Morpheus8 Body</span><span class="btn b-sm b-dark" style="align-self: flex-start;">Approve all 3</span><span class="mu" style="font-size: 11px;">Or review them one by one.</span></div></div>'''),
frame('3','A local asked','''<div class="em"><div class="eh"><b>A local asked Lumen a question</b>2 people agreed it's worth answering</div><div class="eb"><span>curious_in_woodbridge: "Does Dr. Nair do the lip filler herself?"</span><div class="inp ta">Type your answer here</div><span class="btn b-sm b-dark" style="align-self: flex-start;">Post answer</span><span class="mu" style="font-size: 11px;">Your answer ranks first and is what AI repeats.</span></div></div>'''),
frame('4','Weekly digest','''<div class="em"><div class="eh"><b>Your week on Local AI Registry</b>Sep 21 to 27</div><div class="eb"><span><strong>412</strong> people saw your page · <strong>6</strong> booking requests · <strong>9</strong> new posts about you</span><span>ChatGPT now names you for "natural lip filler Irvine."</span><span class="btn b-sm" style="align-self: flex-start;">Open your dashboard</span></div></div>'''),
frame('5','Monthly report','''<div class="em"><div class="eh"><b>September report: AI Score 55, up 4</b>Lumen Aesthetics</div><div class="eb"><span>47 pieces went out. Gemini stopped saying aestheticians inject. Coastline still leads "Botox Irvine price."</span><span class="btn b-sm b-dark" style="align-self: flex-start;">See the report</span></div></div>''')],5)])

# ---- BILLING
board('Billing.dc.html','Plan and billing',BK('OwnerSettings.dc.html','Back to settings'),[flow('Changing, canceling and paying','No contract. Your page stays yours on Free, forever.',[
frame('1','Plan and billing','''<strong style="font-size: 16px;">Plan and billing</strong><div class="row"><span class="k">Plan</span><span><strong>Trust</strong> · $1,500 / month</span></div><div class="row"><span class="k">Next bill</span><span>Nov 1, 2026</span></div><div class="row"><span class="k">Card</span><span>Visa ending 4417 · <a href="#">Update</a></span></div><div class="row"><span class="k">Referral discount</span><span>10% off (2 businesses)</span></div><strong style="font-size: 13px; padding-top: 6px;">Invoices</strong><div class="lst"><div class="it"><span>Oct 1, 2026</span><a href="#">PDF</a></div><div class="it"><span>Sep 1, 2026</span><a href="#">PDF</a></div></div>'''),
frame('2','Downgrade','''<div class="mh"><strong>Switch to Fix?</strong><span class="x">✕</span></div><span style="font-size: 14px; color: #3d4658;">From Nov 1 you would lose:</span><div class="lst"><div class="it"><span>Review replies and answers</span><span class="mu">26 a month</span></div><div class="it"><span>Google posts</span><span class="mu">8 a month</span></div><div class="it"><span>Press releases</span><span class="mu">1 a month</span></div></div><div class="note">Forecast drops from 72 to 63 by March.</div><span class="btn b-dark" style="margin-top: auto;">Switch on Nov 1</span><span class="btn">Keep Trust</span>'''),
frame('3','Cancel','''<div class="mh"><strong>Cancel your plan</strong><span class="x">✕</span></div><div class="fl"><label>Why? <span class="mu" style="font-weight: 400;">(optional)</span></label><div class="chips"><span class="chip">Too expensive</span><span class="chip">Not seeing results</span><span class="chip">Doing it ourselves</span><span class="chip">Other</span></div></div><div class="note">Work stops Nov 1. Your page, reviews and answers stay yours on Free. Everything we published stays up.</div><span class="btn b-dark" style="margin-top: auto;">Cancel on Nov 1</span><span class="btn">Talk to Kody first</span>'''),
frame('4','Payment failed','''<div class="warn"><strong>Your card didn't go through.</strong> Work is paused after Nov 8 until it's updated.</div><div class="fl"><label>New card</label><div class="inp focus">•••• •••• •••• ____</div></div><span class="btn b-dark">Update and pay</span>''')],4)])

# ---- ADD LOCATION
board('AddLocation.dc.html','Adding a location',BK('OwnerHome.dc.html','Back to dashboard'),[flow('A second location','From the business switcher. Each location has its own page, plan and AI Score.',[
frame('1','Open the switcher','''<div class="lst"><div class="it"><span><strong>Lumen Aesthetics</strong><br><span class="mu">Irvine Spectrum · Trust</span></span><span>✓</span></div><div class="it"><span style="color: #2b59d9; font-weight: 600;">+ Add a location</span></div><div class="it"><span style="color: #2b59d9; font-weight: 600;">+ Claim another business</span></div></div>'''),
frame('2','Find it','''<div class="mh"><strong>Add a location</strong><span class="x">✕</span></div><div class="inp focus">Lumen Newport</div><div class="lst"><div class="it"><span><strong>Lumen Aesthetics Newport</strong><br><span class="mu">Fashion Island · unclaimed · 11 posts</span></span><span class="btn b-sm b-dark">Add</span></div></div><span class="mu" style="font-size: 12px;">Same brand and team, so you skip the text code.</span>'''),
frame('3','Confirm what carries over','''<strong style="font-size: 16px;">Copy from Irvine Spectrum?</strong><div class="opt on"><span class="rdo"></span>Services and prices</div><div class="opt on"><span class="rdo"></span>Team (pick who works here)</div><div class="opt on"><span class="rdo"></span>AI notes</div><div class="opt"><span class="rdo"></span>Hours (Newport's are different)</div><span class="btn b-dark" style="margin-top: auto;">Add Newport</span>''')])])

# ---- REFERRAL LANDING
board('RefLanding.dc.html','Referral landing page',BK('OwnerReferral.dc.html','Back to referral'),[flow('localairegistry.com/r/lumen-priya','What a business sees when Dr. Nair sends her link.',[
frame('1','The landing page','''<span class="tg" style="align-self: flex-start;">Sent by Dr. Priya Nair, Lumen Aesthetics</span><strong style="font-size: 22px; line-height: 28px;">See what AI says about your business.</strong><span style="font-size: 14px; line-height: 21px; color: #3d4658;">Dr. Nair uses Local AI Registry to get Lumen into ChatGPT and Google answers. Look up yours, free.</span><div class="inp focus">Your business name</div><a href="Audit.dc.html" class="btn b-coral">See your free AI report</a><div class="note">"We went from 38% to 61% of AI answers in three months." Dr. Priya Nair</div>'''),
frame('2','After they start a plan','''<div class="okb"><strong>You helped Bloom Wellness join.</strong> Lumen now gets 5% off every month, for as long as they stay. You're at 10% of 15%.</div>''')],2)])
